### ISSUE TITLE
Feature Request: Add "Start PowerShell..." to File Menu

### ISSUE THREAD

**Issue by markekraus** [Microsoft/winfile#1]
This is great! I think this could really improve several of my workflows. I'd love to see a "Start PowerShell..." option added to the start menu.

**Comment by craigwi** [comment]
Good idea.

**Comment by craigwi** [comment]
What shortcut key should I bind to this command?  ^p ?

**Comment by gbraad** [comment]
@Allen-Wei I guess he meant `s/start menu/file menu`.

**Comment by DC-Shi** [comment]
Maybe one more `Shift` would change CMD to PowerShell ?

**Comment by craigwi** [comment]
ctrl+p it is.  @markekraus, check out https://github.com/Microsoft/winfile/tree/fixissue1 and let me know if that works for you.  If so, I'll integrate to master.

**Comment by markekraus** [comment]
@craigwi I can't speak for the powershell.exe detection as I'm not familiar with C registry APIs, but the rest LGTM!

**Comment by TrestleMonkey** [comment]
It seems there's a little bug with this (and also the "Start Cmd Shell" command) is that if nothing has been selected yet in either the tree or file list then it crashes.  The call to `GetSelection(...)` returns NULL and this isn't checked.  I guess in this case it should fall back to the current directory being shown in the selected window.
