### ISSUE TITLE
Winfile won't start since commit (dc4c149f1b0ba5e1a628b5e40557726640c710ef) under Windows 7

### ISSUE THREAD

**Issue by BaldwinTechnology** [Microsoft/winfile#102]
![ms-api](https://user-images.githubusercontent.com/38319355/38810804-227276fa-4188-11e8-870f-a874916d50f3.png)

The program can't start, because api-ms-win-core-wow64-l1-1-0.dll is missing on your computer. Install the program again to solve this problem.

I have build the newest Commit (d024133a4816e42348ac7bc1a286fc037df90f0a): add GNUmakefile for build on mingw (#93)
and it doesn't start. But it builds.

The last commit which works is (af4b76e7c8d7a46d8d0f73572cfc3f4a7df990e3): Various improvements from PR #55.

I think is has something todo with the use of mincore.lib

System:
Windows7 with VisualStudio 2017 and
Windows SDK Version: 10.0.15063.0
Platform Toolset v141

Edit:

**Replace mincore.lib from linker settings with version.lib**

The online help for GetFileVersionInfo(), for example, has, for 4 years now, incorrectly listed mincore.lib as being required. It isn't; the correct one is version.lib. Perhaps you have a similar problem with misinformation.

Source: https://social.msdn.microsoft.com/Forums/vstudio/en-US/a28331ae-19a3-4a34-b3ba-1e8fd4430375/missing-apimswincore-dlls?forum=windowsgeneraldevelopmentissues

**Comment by BaldwinTechnology** [comment]
Additional info found on:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/a28331ae-19a3-4a34-b3ba-1e8fd4430375/missing-apimswincore-dlls?forum=windowsgeneraldevelopmentissues


As you said, the API Sets sound like they might be. The "umbrella" libs in API sets, MinCore.lib and MinCore_Downlevel.lib are provided in the Microsoft Windows Software Development Kit (SDK) that encompasses the API surface defined in API Sets plus additional APIs that are contained in well-layered system DLLs. So try include MinCore.lib and MinCore_Downlevel.lib maybe useful. I have search in my win7 and these are in SDK directory.  But notice that binaries that link to MinCore.lib or MinCore_Downlevel.lib **are not designed to work on Windows 7.**

No more Windows 7 support?

**Comment by craigwi** [comment]
@matthewjustice, would you look at the above comment about mincore.lib?  Can we version.lib?

**Comment by matthewjustice** [comment]
@BaldwinTechnology - Good catch. I submitted PR #103 to address this as you recommended, and it works on Windows 10, but I haven't had a chance to verify on Windows 7 yet. 

@craigwi - I guess I need Windows 7 in my test matrix!

**Comment by ZanderBrown** [comment]
@craigwi  Could we setup a CI which dumps compiled executables to somewhere publicly accessible?

That would allow us to easily check a PR on the various systems each of us have access to without requiring us to built it individually

**Comment by craigwi** [comment]
Good idea. @iamkarlson suggested using appveyor.com (in that case for chocolatey integration).  Would that work for your needs?

**Comment by ZanderBrown** [comment]
@craigwi sounds fine

**Comment by NazmusLabs** [comment]
I can use this opportunity to test the latest commit in Windows 7 to see if it runs as well as Visual Styles...if that made it in.

**Comment by BaldwinTechnology** [comment]
Tested and works now under Win 7. (ba9c7029e1e488579190d460de7543f81ba054e8)

**Comment by BaldwinTechnology** [comment]
All is fine.

**Comment by matthewjustice** [comment]
@BaldwinTechnology Thanks for testing!
