### ISSUE TITLE
Unicode only

### ISSUE THREAD

**Issue by DBJDBJ** [Microsoft/winfile#109]
Why not just have WinFile unicode only?

**Comment by craigwi** [comment]
That's how it compiles today for Windows 10.

**Comment by DBJDBJ** [comment]
@craigwi thanks. But then I am asking myself why not just dropping tchar.h and friends?
As for other versions I assume "even" on XP, unicode build will work just fine.  
I dare to think even Win 2000 familly will be ok with unicode build.
As an example cppWinRT is pure unicode. 
After all it seems WinFile will be UWP App.. That would clarify the WinFile roadmap. A lot.

**Comment by craigwi** [comment]
Thus far, this project are looking at three things:

1. ensuring WinFile runs on several versions of Windows including Win 3.1, WinXP, Win 7 and Windows 10
2. fixing specific simple and obvious issues (e.g., spelling, automated checks, visual styles)
3. improving basic features (e.g., about dialog).

Narrowing the focus to Unicode only or UWP only are currently a priority.  In fact, none of the efforts above include removing support for non-Unicode environments.

Hopefully that clarifies the current efforts here.  A lot.

**Comment by DBJDBJ** [comment]
"...Narrowing the focus to Unicode only or UWP only are currently a priority..."

@craigwi  me slightly confused :) your answer means we are in agreement... Unless you wanted to type "not a priority"?

**Comment by ZanderBrown** [comment]
I suspect typo

**Comment by craigwi** [comment]
Yes, a typo.  Should have been: "Narrowing the focus to Unicode only or UWP only are not currently a priority. "
