### ISSUE TITLE
Is winfile.rc broken?

### ISSUE THREAD

**Issue by CNAmira** [Microsoft/winfile#11]
I can't open it in any plain text editor.

**Comment by msphn** [comment]
use an hex editor

**Comment by CNAmira** [comment]
But it isn't a valid rc file.

**Comment by daniel-white** [comment]
I tried opening in 2017 saying one of the IDs was too long.

**Comment by craigwi** [comment]
This file is not used and I will remove it.

**Comment by daniel-white** [comment]
@craigwi oh i got my names crossed `res.rc` is busted with the SYMBOL too long.

**Comment by craigwi** [comment]
winfile.rc has been deleted from master.
