### ISSUE TITLE
No Toolbar-Buttons since (49597b8c423b8e8d16ee252adc1e6e8f69e8c1ac)

### ISSUE THREAD

**Issue by BaldwinTechnology** [Microsoft/winfile#111]
Hi,

the toolbar **buttons** are gone with the checkin (49597b8c423b8e8d16ee252adc1e6e8f69e8c1ac) 

Squashed commit of the following: 
16. April 2018 10:44:13

Only the pictures are left. Is this a Win7 only behavior or a preparation for visual styles?

The following lines are addes in winfile.c

`#pragma comment(linker, "\"/manifestdependency: \`
`    type = 'Win32'                              \`
`    name = 'Microsoft.Windows.Common-Controls'  \`
`    version = '6.0.0.0'                         \`
`    processorArchitecture = '*'                 \`
`    publicKeyToken = '6595b64144ccf1df'         \`
`    language = '*'                              \"")`

Greetings
Daniel

**Comment by thecatkitty** [comment]
It is not a bug. Moreover, it is an **intended part** of using the visual styles.

**Comment by BaldwinTechnology** [comment]
I have supposed something.
But how can I get the old style back?

**Comment by thecatkitty** [comment]
I am not sure, but perhaps setting __Disable visual themes__ in winfile.exe compatibility properties will help?

**Comment by ZanderBrown** [comment]
@thecatkitty that may help but I seem to remember that disables Aero as well?

Having this as an option should probably be investigated

**Comment by thecatkitty** [comment]
@ZanderBrown Windows _of course_ [enables us to do that](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773175(v=vs.85).aspx#turnoff). We might add such option to the menu (it starts to seem like the _Preferences_ dialog could become a good thing to add) but it would create a dependency on `uxtheme.dll`... Shall we use LoadLibrary then?

**Comment by Biswa96** [comment]
First check if that API works for WinXP or Vista.

**Comment by ZanderBrown** [comment]
Yes LoadLibrary would seem the way to go, I think for now the Options menu is fine but maybe we should have a separate dialog for all the additions over the original WinFile features

**Comment by NazmusLabs** [comment]
This issue has been now fixed in the latest commit. I think this can be closed.
