### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by T8z5h3** [Microsoft/winfile#123]
Hi,
I see a lot of work being done but I would like to know when is the next version getting released or how do I even build the source into a useable version?

**Comment by craigwi** [comment]
We are looking at a few different options for releasing WinFile -- appveyor, Windows Store, some internal Microsoft thing, and direct to github.

To build master for Windows 7+, use VS 2015 or 2017, load src\WinFile.sln and press F6.

**Comment by T8z5h3** [comment]
The other option is though windows update like they do with office?

**Comment by T8z5h3** [comment]
2nd question is the v10 branch getting updated or the other branch?

**Comment by thecatkitty** [comment]
@T8z5h3 Using Microsoft Update is certainly not an option. It would probably rely on **a lot** of negotiations with MsU division/team/folks and would really make some limitations for us (like, probably, impossibility for per-user installation, no support for older OS-es, publishing Microsoft Knowledge Base articles). I think it isn't a thing to happen.

And we've got only one branch right now.

**Comment by NazmusLabs** [comment]
@T8z5h3 the Windows Store's auto updating system will essentially take care of that need. If you are running Windows 10, that should be sufficient. You don't even need a Microsoft account to be able to use the store version and get automatic updates.

**Comment by T8z5h3** [comment]
@NazmusLabs what about windows 7

**Comment by T8z5h3** [comment]
@craigwi i wonder if sysinternals maybe willing to host it they have a lot of "admin" level tools that are not directly supported by Microsoft.

**Comment by craigwi** [comment]
As noted elsewhere, we will have a few different distribution mechanisms. Windows Update will not be one of them.
