### ISSUE TITLE
Statusbar is missing on wine

### ISSUE THREAD

**Issue by ZanderBrown** [Microsoft/winfile#13]
On Wine 3.4 the status bar doesn't seem to be rendered
![screenshot from 2018-04-09 15-27-35](https://user-images.githubusercontent.com/17074021/38503663-93730582-3c0a-11e8-8e4b-628de67aaff2.png)

Any chance we could have the original Makefiles as well as the VS solution?

I'm unable to build from a `.sln` and #9 will be challenging without Makefiles as well

**Comment by badsectoracula** [comment]
Shouldn't this be filed against Wine? After all it is supposed to be bug-for-bug compatible, this is an example where it isn't the case and the developers can check the source code of WinFile to see why. I think it is better to file this against the Wine developers so that they can make their implementation behave like Windows does than alter WinFile to make it work better with Wine.

**Comment by ZanderBrown** [comment]
Sure, point still remains about Makefiles though

**Comment by craigwi** [comment]
Regarding the makefiles, the project originally used a Microsoft internal build system.  The primary file in the project used to describe building WinFile.exe was called 'sources'.  That file contained the same information now in the vcxproj.  The original 'sources' file is attached (renamed to .txt for upload).

[sources.txt](https://github.com/Microsoft/winfile/files/1890665/sources.txt)

**Comment by sskras** [comment]
It would be nice to have the issue renamed then:)

**Comment by ZanderBrown** [comment]
Without knowing this internal build system it looks like Autotools style macros for generating a Makefile

Might get vc++ out and make them 'real'

**Comment by ir0nlake** [comment]
The internal build system is known as Razzle. Razzle uses a makefile.def Nmakefile in \public\oak\ which is included from the source level makefile (in this case .\makefile), that includes .\sources, which then compiles/links source code from variables in .\sources into a executable using the rules inside of makefile.def.

You can actually see bits of razzle in the Windows DDKs (which, really are just razzle without developer profile and source control support, as well as not shipping with library source code), especially older ones like NT4-Srv03.
