### ISSUE TITLE
OS X64 version

### ISSUE THREAD

**Issue by new518fa** [Microsoft/winfile#144]
Can make a x64 version? thank you.

**Comment by thecatkitty** [comment]
This is easily compilable as x64, but I think You mean having x64 release to download?

**Comment by new518fa** [comment]
Yes,  Can downloaded, there are a lot of warnings with VS2017 Compiled x64 version

**Comment by NazmusLabs** [comment]
Yes, I believe we should provide both x64 and x86 versions for the next release.

**Comment by craigwi** [comment]
Coming soon!

**Comment by craigwi** [comment]
"choco install winfile -pre" installs a x64 bit release from a few days ago.  Once I get the signing to work, I will submit another pre-release package.  Once we get the versioning scheme decided, I will submit a real package.  All of the new packages will include an x64 version.

**Comment by NazmusLabs** [comment]
@craigwi when creating a release package, we should exclude the winhelp file, as it is not supported on the OSes it targets. That can stay as part of the retro releases. Including that just unnecessarily adds total package size.

**Comment by craigwi** [comment]
makes sense.

**Comment by craigwi** [comment]
FYI: The CI build for x64 is here: https://winfilerelease.blob.core.windows.net/craigwi/x64/Winfile.exe

**Comment by craigwi** [comment]
I'll leave winfile.hlp out of future releases.
