### ISSUE TITLE
"Start Cmd Shell" poses security breach

### ISSUE THREAD

**Issue by krankenbyte** [Microsoft/winfile#153]
"Start Cmd Shell..." command runs cmd.exe using relative path. This approach poses security breach: if current working directory contains a malicious cmd.exe file (hidden one likely), starting cmd shell runs this malicious file instead of running Windows' cmd.exe in C:\System\.
I suppose the application should use absolute path to cmd.exe.

**Comment by peterooch** [comment]
Already addressed in PR #23

**Comment by craigwi** [comment]
Agreed.

**Comment by NazmusLabs** [comment]
@peterooch I find the fix to be overly complicated with functions to extract absolute path. I would think using %windir%\system32\cmd.exe is much more efficient than doing all the if functions. Thoughs?

**Comment by mdmannan179** [comment]
apt-get install git
