### ISSUE TITLE
Keyboad shortcuts broken

### ISSUE THREAD

**Issue by TubaOrNotTuba** [Microsoft/winfile#16]
In all previous versions of winfile.exe, CTRL-C, CTRL-D, CTRL-E, CTRL-F, etc... would take you to that drive letter. Now they appear to be Office-style shortcuts where, for example, CTRL-F is a search dialog.  Why would these be changed?  I just tested this on an NT 4.0 VM and confirmed that the CTRL-x combinations do work as I remembered.

**Comment by joekohlsdorf** [comment]
Please read the readme, it explains everything.

Answer: You are using the wrong branch.

**Comment by TubaOrNotTuba** [comment]
This is the content of the readme file:

WinFile release v10.0.  See readme.md for changes.

Files:
winfile.exe, winfile.pdb: release build for x86 (32bit)
winfile.chm: copied from help directory

Hash:
winfile.exe sha1 D9D9D15B6EF0FC483417461A1844AB6C2A532656

Runtime:
Winfile.exe depends on the VS 2015 C++ runtime; you can download that from
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by TubaOrNotTuba** [comment]
Ok, so "control characters (e.g., ctrl+C) map to current short cut (e.g., ctrl+c -> copy) instead of changing drives" but that's just crazy.  That'd be like re-releasing Donkey Kong with 2018 graphics.  

You say I'm on the wrong branch, is there one that keeps all the features of the old winfile.exe without the changes that really make it far less functional?

**Comment by ZanderBrown** [comment]
Yes it would be good to have an 'untouched' branch so we can:
A: see what's changed
B: compile this on/for Win3x

**Comment by TubaOrNotTuba** [comment]
I just don't see the purpose to modernize File Manager.  All the tools they've added to it here are already available in File Explorer so leave File Manager alone.  I always made the bet that for $100, I could do 100 file management operations faster than anyone at Microsoft could do in Explorer but no one in Redmond ever took me up on it.  I still can do it using XP/2003 up against anyone on 10/2016 but with this build so much of the functionality has been dummied down it's now just fun to look at, it's not really a functional tool.

**Comment by craigwi** [comment]
You can find the original source with minimal changes (and which retains the original shortcuts) in the release: https://github.com/Microsoft/winfile/releases/tag/original_plus.  I even created a binary for you.

Have fun!
