### ISSUE TITLE
How to change this application language?

### ISSUE THREAD

**Issue by itning** [Microsoft/winfile#160]
I did not find this option in the settings.

**Comment by mattn** [comment]
See Menu -> Option -> Additional Preferences

**Comment by itning** [comment]
I am sorry I did not find this option.

![options](https://raw.githubusercontent.com/itning/FilePool/master/images/options.PNG)

**Comment by peterooch** [comment]
You need to build from the current source or download it from the links provided in issue #7, they are near the bottom.
