### ISSUE TITLE
Toolbar Customization Does Not Load

### ISSUE THREAD

**Issue by RMoDOOM** [Microsoft/winfile#164]
I cannot get my toolbar customizations to load from the registry, with any solution configuration.

While modifying the toolbar I can see the registry entry update (it's binary, but it does change immediately), so the changes are being saved, but upon restarting Winfile the customizations are not loaded. The customizations do stay in the registry, however.

In tbar.c,:412, the `bRestored ` always returns false when I run it through debug. That's about the limit of my knowledge; I work primarily with .NET so I'm not used to the whole message-sending that C++ does for UI.

Any ideas?

**Comment by ZanderBrown** [comment]
Yes **C** is quite different from the niceties of WinForms (and higher)

At somepoint we seem to have got some registry stuff creep in whilst still using .ini api (which generally just wraps the registry these days) so perhaps something is conflicting

I'm seeing this happen on Wine

**Comment by RMoDOOM** [comment]
I forgot to mention, I'm on Windows 10 Enterprise 1709.16299.371

And yes, C. My bad, haha. 😜

**Comment by craigwi** [comment]
He @RMoDOOM, can you try your toolbar customizations again?  I might have gotten lucky and fixed your issue with my recent changes.  Let me know.

**Comment by RMoDOOM** [comment]
Unfortunately it doesn't appear to have been fixed. I still can't customize the toolbar.

**Comment by craigwi** [comment]
Ok, @RMoDOOM  can you share the specific customization you are using?  I will try to reproduce the issue.

**Comment by RMoDOOM** [comment]
It's been every customization I've tried. Nothing specific seems to trigger it. I can remove all buttons from the default toolbar, add one button, completely rearrange it, add each button one by one, and whenever I restart the program it's gone.

**Comment by craigwi** [comment]
I figured this out; per https://docs.microsoft.com/en-us/windows/desktop/Controls/customize-toolbars the save/restore method changed to use TBN_SAVE/TBN_RESTORE instead of TBN_GETBUTTONINFO.  Default behavior of TBN_SAVE writes the "Shell-defined data", but TBN_RESTORE doesn't do anything with it (nor should it).  That's why you see the data in the registry, but it is ignored.

I've started on a fix, but the existing code is pretty convoluted due to extensions with toolbars.

**Comment by craigwi** [comment]
I implemented the new(er) toolbar save/restore mechanism.  @RMoDOOM, your case should work now; if not, let me know.

As a reminder, the current builds are located on:
https://winfilerelease.blob.core.windows.net/craigwi/Win32/Winfile.exe
https://winfilerelease.blob.core.windows.net/craigwi/x64/Winfile.exe

**Comment by RMoDOOM** [comment]
Yep, that seems to have solved my issue. Thanks!
