### ISSUE TITLE
Security options gone, please return

### ISSUE THREAD

**Issue by TubaOrNotTuba** [Microsoft/winfile#17]
One of the best things to use File Manager for, and I maintain a Win2003/XP VMs just for this issue, is to fix the sometimes ridiculously complex file/folder permissions issues found in Windows Vista/2008 and later builds.  Since File Manager doesn't understand or respect inheritance I even saw Microsoft support engineers use it to fix broken permissions issues back in the day.  

I vote for adding back the Security menu and its submenus from the last build of winfile.exe from NT 4.0 days.  I'd love to be able to never have to boot a 2003/XP VM again for this purpose.  Yes, I get it, there are other options, but NONE as direct and concise as using File Manager to fix the system that Microsoft never bothered to fix on its own.

**Comment by craigwi** [comment]
In the latest build you can use Alt+Enter to get to the "normal" properties of an item, which includes a Security tab.  Does that meet your needs?

**Comment by craigwi** [comment]
@yuhong you are correct.  See wfinfo.c, line 1781: acledit.dll is still loaded, but the call to get FMExtensionProcW entry point fails and thus the Security menu is deleted.  BTW, I fixed a bug early on here: if the child window was maximized at startup, the wrong menu was deleted.

Thus, all of the old functionality as present in this code base remains.

I suppose I could dig around for the sources to acledit.dll.

**Comment by ZanderBrown** [comment]
Open Sourcing Win3/NT4 one component at a time...

If your taking requests Program Manager might be nice :laughing:

**Comment by yuhong** [comment]
I wonder if Progman was killed in XP SP2 because of security BTW, given that it had to parse .grp files.

**Comment by craigwi** [comment]
@ZanderBrown what would be a full time job!  I already have one.
