### ISSUE TITLE
About MAXLFNPATHLEN

### ISSUE THREAD

**Issue by clzls** [Microsoft/winfile#170]
Now MAXLFNPATHLEN (aka MAXPATHLEN) is defined as 260. So Winfile can't handle some very deep / very long paths, which is more common for our CJK character users (about 120 CJK characters + 20 symbols (for example `E:\` and spaces); and when romanized some CJK words will be even longer. I haven't find a path so long in English environment beside those in AppData containing several GUIDs.)

Like this:
E:\Personal Stuff\E-Books\Gong Ju Shu\Fu Zhou Fang Yan Can Kao Zi Liao\icesunxZheng Li Zhi Zuo .Yuan Wen Ji\Fu Zhou Fang Yan Ci Dian (16)\Fu Zhou Fang Yan Ci Dian - icesunxZheng Li Zhi Zuo .Yuan Wen Ji\Fu Zhou Fang Yan Ci Dian - 1994 Zui Xin Xiu Ding Ban Ben Bei Fen\

So should we extend it a little bit? Or just ignore this problem?
And should it give out a notification rather than crashing silently when path length meets MAXPATHLEN?

**Comment by clzls** [comment]
Duplicated with #50 . Closing this issue.

**Comment by schinagl** [comment]
See #340
