### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by clzls** [Microsoft/winfile#172]
Since last release, we added language support for zh-CN, ja-JP, he-IL, pl-PL.
> 116 commits to master since this release
> 10,152 additions and 2,722 deletions

This project has drown more and more attention in China. Since there's no Chinese support in release v10.0, they had to download 3rd-party builds and so we could not get responses from users.
It's time to have a multi-lingual release now.

Update: If using 3rd-party distribution service like `choco` as issue #7 said is now the official way of distribution, please add a tip to the `README.md`.

PS. Can we have a small updater embedded in Winfile?

**Comment by ad43** [comment]
> PS. Can we have a small updater embedded in Winfile?

I think I am suffering from update overload, what with my phone looking different every morning, Windows behaving like a snake that must slough off its skin and renews itself every few months and browsers that become 'deprecated'. I am just glad that my car doesn't decide to upgrade its leather seats to environmentally-friendly bamboo cloth overnight. At least, not yet.

Be gentle with updates. Not everyone wants to be included every time.

Chris

**Comment by clzls** [comment]
> renews itself every few months and browsers that become 'deprecated'.

such 'update' is certainly annoying worldwide now (smile). I hate it too.

But as a non-English speaker, a better translation is always needed. Since the language system isn't completed, it just like a car without air conditioner. It's fine in America in most of time but if in Africa in summer or Canada in winter you may feel sick. You English users won't feel any different with or without a better translation (because it was made in English from beginning); but others, Germans, Chinese, Japanese, etc. will be unhappy about broken language.

Not everyone is eager for updates, but some does. And this updater, I think, can be a optional tool that won't disturb users who don't need a update. (Not a Windows 10 style LOL) Or just throught `choco`, I think.

**Comment by craigwi** [comment]
As noted in #7 (https://github.com/Microsoft/winfile/issues/7#issuecomment-384032280), I am planning on three distribution methods.  The first two methods are done.  The third, Microsoft Store, has not been completed.

You can install the latest release via Chocolatey with the command 'choco install winfile --version 10.0.1805.1'.

**Comment by clzls** [comment]
@craigwi You misunderstood my idea. I've said that,
> If using 3rd-party distribution service like `choco` as issue #7 said is now the official way of distribution, **please add a tip to ``README.md``.**

Not everybody, especially normal users will go through the issue list to find how to get a new **_stable_** build.
So we should release a new **_stable_** version for users.

**Comment by craigwi** [comment]
You are right; I need to update the readme.md.  Thanks for mentioning that.
