### ISSUE TITLE
About SEARCHDLG

### ISSUE THREAD

**Issue by clzls** [Microsoft/winfile#173]
While translating SEARCHDLG into Chinese, I found that I could not translate "Since" into Chinese (maybe for the same reason it was left untranslated there). I referred to Help but nothing helpful. So what this "Since" (and "Start From") here actually mean?

![image](https://user-images.githubusercontent.com/16474386/40155146-af33a376-59c4-11e8-9530-3cca3e5ff4f1.png)

**Comment by craigwi** [comment]
The value provided for "since" is a date and when provided it means that Winfile is to find all files modified after the value.  So if I provided "Jan 1, 2018", Winfile would find all files (matching the other conditions too) which were modified after Jan 1, 2018.  Does that help?

**Comment by clzls** [comment]
Yes, that greatly helps. Another question: Is the date format same as that in locale settings? or, does it accept "2018-12-31" or "2018.12.31" as we use them in China?
________________________________

**Comment by BaldwinTechnology** [comment]
Would be a date control suitable for this (the since) entry?

**Comment by craigwi** [comment]
I'm fine with a date control, but not sure of the added value.  Currently the code in wfdlgs2.c uses VarDateFromStr which takes the locale.  I assume this means locale specific parsing works, but haven't tried it.  @clzls, does it work for the way you enter dates?

**Comment by clzls** [comment]
@craigwi can't you see my updates of my last comment? Okay, I will post it here:

Update: It can process "2018-12-31" but not "2018.12.31" or "2018年12月31日". To make its meaning clear, I think adding a tip(for example provide a default date of "2018-05-19") or a date control is a good idea.

In Chinese, we translate "Since" as "...之后"(From ... on), which is a vague expression. To make it clear, we must use the expression "在以下日期后修改过"(Modified after this date) or "最后修改日期晚于"(Last Modified Date is after this date), which are 3x longer than original English expression. The extension of the dialog is needed. (I may do this this weekend or later on, but if a date control is added, I may delay it.)

**Comment by craigwi** [comment]
Hi @clzls, I had not seen the updates to your comment.  Thanks for highlighting them.

So, we need to look for another means to parse locale-specific dates.

**Comment by ZanderBrown** [comment]
Perhaps we aren't using the right [flags](https://msdn.microsoft.com/en-gb/library/windows/desktop/ms221395(v=vs.85).aspx)?

**Comment by clzls** [comment]
>Perhaps we aren't using the right flags?

@ZanderBrown , maybe not. In fact, it works very well. It's just not so convenient, through.
A date control is more convenient, I think.
@craigwi , I've found that `2018.05.21` is not a locale-based date in Microsoft's database. so this bug is system-wide.

**Comment by ZanderBrown** [comment]
@clzls would you describe it as a common format?

**Comment by clzls** [comment]
@ZanderBrown Sorry for misunderstand your words. It's commonly used _here_; but `YYYY/MM/DD`, `YYYY.MM.DD`, `YYYY-MM-DD`, `YYYY_MM_DD` and many other formats are all commonly used. In other words, there's no standard or a common usage. Many of them is not in the locale database of MS. I think it's not a problem; I guess few people will refuse `2018-05-22` and insist on `2018.05.22` if the program told him to use `2018-05-22` format.

So, we should have a `MessageBox` when `VarDateFromStr` fails, which is more important than trying to read `2018.05.22` when Windows won't recognize them as dates.
After that, we can talk about adding a date control or so.

I will close this issue now, because the problem presented in the issue is solved. If you think we should continue discussing, I can reopen it.
