### ISSUE TITLE
add / restore hot keys to select drives

### ISSUE THREAD

**Issue by ScottHollows** [microsoft/winfile#181]
The original hot keys to select drives no longer work.

Ctrl C - select C:
Ctrl D - select D:
Ctrl E - select E:

I know that Ctrl C / X / V have been repurposes for copy / cut / paste so that they arent available for drive selection any longer

Could another hotkey combination be added ? such as Shift Control C / D / E 

Thank you for this effort.  It is very much appreciated from this long time File Manager user

**Comment by richardboegli** [comment]
@ScottHollows as an interim solution until this is implemented, you could do the following:
ALT+D, S then key for drive letter, then Enter.
OR
You could even use this with AutoHotKey / AutoIT to implement Shift Control C / D / E.

ie: CTRL+SHIFT+C would trigger AutoHotKey keypress sequence

`#InstallKeybdHook`
`SendMode Input`
`SetWorkingDir %A_ScriptDir%`
`#IfWinActive, File Manager`
`^+c::`
`{`
`Send {ALTDOWN}{D}{S}{ALTUP}`
`Send {C}`
`Send {ENTER}`
`Return`
`}`

**Comment by ScottHollows** [comment]
Thanks Richard

Seeing as some of the ALT and CTRL keys are already in use this is a reasonable workaround.

I have modified your script to work with multiple drives with C and D as an example.
This is a reasonable workaround so I think this enhancement request can be closed
`
#InstallKeybdHook
SendMode Input
SetWorkingDir %A_ScriptDir%

#IfWinActive, File Manager
	{
	$^C::				; Ctrl C
		{
		Send {ALTDOWN}{D}{S}{ALTUP}
		Send {C}
		Send {ENTER}
		Return
		}
	$^D::				; Ctrl D
		{
		Send {ALTDOWN}{D}{S}{ALTUP}
		Send {D}
		Send {ENTER}
		Return
		}
	}`
