### ISSUE TITLE
modify Goto Directory to support other drives

### ISSUE THREAD

**Issue by ScottHollows** [microsoft/winfile#183]
The new Goto Directory is handy - thank you for adding that

Adding support for other drives would be useful

We dont nescecarily want to index all drives as that could result in scanning large network drives, so perhaps an option to specify which drives should be indexed would be handy

**Comment by schinagl** [comment]
#293 allows you to specify a command separated list of path to index.
You can configure this via Winfile.ini[Settings]CachedPath. e.g. 

`CachedPath=D:\;c:\mypath`

**Comment by malxau-msft** [comment]
Can we close this? Are there additional changes needed/wanted?

**Comment by ScottHollows** [comment]
Closing.  Resolved by 293
