### ISSUE TITLE
ARM32 WinRT dynamic link issue

### ISSUE THREAD

**Issue by hooddy** [microsoft/winfile#185]
Can ya change dynamic link to static link so it doesn't need to use msvcp140.dll and vcruntime140.dll please?

Also add link to donwload arm release at release section please.

**Comment by ZanderBrown** [comment]
We've had this discussion before

**Comment by hooddy** [comment]
But it still need it. Maybe i didnt get it. So it stay as it?

**Comment by kent7301** [comment]
What does it mean ?


Отправлено из мобильной Почты Mail.Ru


пятница, 22 июня 2018 г., 0:57 +0400 от notifications@github.com  <notifications@github.com>:

**Comment by ZanderBrown** [comment]
Not sure but general opinion was negative when we discussed static linking

Generally a bit catch 22 really

**Comment by kent7301** [comment]
Can I find out who I'm talking to?



Отправлено из мобильной Почты Mail.Ru


пятница, 22 июня 2018 г., 1:16 +0400 от notifications@github.com  <notifications@github.com>:

**Comment by ZanderBrown** [comment]
What do you mean? Your currently talking to a public GitHub issue so to some extent your talking to everyone.

Do you have anything to add to the conversation or are you lost/confused....?

**Comment by hooddy** [comment]
Ok it very usable in current state. Thanks a lot anyway for build this.

**Comment by kent7301** [comment]
I do not need to respond to your notifications

Отправлено из мобильной Почты Mail.Ru


пятница, 22 июня 2018 г., 1:50 +0400 от notifications@github.com  <notifications@github.com>:

**Comment by kent7301** [comment]
Отправлено из мобильной Почты Mail.Ru


пятница, 22 июня 2018 г., 1:50 +0400 от notifications@github.com  <notifications@github.com>:

**Comment by craigwi** [comment]
The plan as last discussed was to use chocolatey and Windows Store, both of which support dependency installation.  The current chocolatey build does not include the ARM binaries, but then I'm not sure of chocolatey supports ARM.  If so, I will update the package.

The Windows Store release remains in progress (had some other projects take priority for a bit).

**Comment by hooddy** [comment]
@craigwi ok but I doubt Windows Store accept ARM32 version for WinRT. MS try to drop down all of dead systems (Win7/8 etc as well as Wp8/W10M). So please just update ARM32 version in any you preffered way. And anyway Windowsstore for Win10/ARM is not the same that Windows Store for Win8/RT. So I think you faced with some troubles n separate branch distribution.

**Comment by woachk** [comment]
You can just install the VS2017 redistributable on Arm, it's the same as on x86/x64. I have the vcredist.exe if you don't have it already @hooddy

**Comment by malxau-msft** [comment]
Closing this as I think the move to ARM64 has made it moot.  ARM32 was a challenge because there was no official redist DLL installer for it - we were using it in a not-really supported way to generate Desktop applications.  ARM64 is supported for this purpose, and the redist DLL works the same there as on x86/x64.
