### ISSUE TITLE
Rename file case not recognized by various features

### ISSUE THREAD

**Issue by ScottHollows** [microsoft/winfile#186]
After renaming a file to change its case (upper to lower), most of the Menu / File options show the old file name instead of the new file name

Steps to reproduce

1) create a file ABC.txt

2) Use Menu -> File -> Rename to rename the file to abc.txt (changing its case from upper to lower)

3) Open these dialogs.  Note that the old file name ABC.txt is shown instead of the new file name abc.txt
- Menu -> File -> Move
- Menu -> File -> Copy
- Menu -> File -> Delete
- Menu -> File -> Rename

These are just the features that I tested. 
I expect other features also use the old file name instead of the new file name

**Comment by ZanderBrown** [comment]
https://stackoverflow.com/questions/33998669/windows-ntfs-and-case-sensitivity

**Comment by craigwi** [comment]
I went through the steps above and the new name (lower case) is shown as expected.  Thus I am closing this as not repro.
