### ISSUE TITLE
Как выставить приоритет процессу через Python?

### ISSUE THREAD

**Issue by loganili** [Microsoft/winfile#196]

**Comment by ZanderBrown** [comment]
Of winfile or something else?

Winfile isn't written in Python (although they are about the same age)

*Disclaimer: Bing Translate was used*

**Comment by Askalion** [comment]
def new_privs():
    new_privs = (
        (
            win32security.LookupPrivilegeValue("", win32security.SE_SECURITY_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue("", win32security.SE_TCB_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue("", win32security.SE_SHUTDOWN_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue("", win32security.SE_RESTORE_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue("", win32security.SE_TAKE_OWNERSHIP_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue("", win32security.SE_CREATE_PERMANENT_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue("", win32security.SE_ENABLE_DELEGATION_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue("", win32security.SE_CHANGE_NOTIFY_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue("", win32security.SE_DEBUG_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue(
                "", win32security.SE_PROF_SINGLE_PROCESS_NAME
            ),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue("", win32security.SE_SYSTEM_PROFILE_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
        (
            win32security.LookupPrivilegeValue("", win32security.SE_LOCK_MEMORY_NAME),
            win32con.SE_PRIVILEGE_ENABLED,
        ),
    )

    ph = win32process.GetCurrentProcess()
    th = win32security.OpenProcessToken(ph, win32security.TOKEN_ALL_ACCESS)  # win32con.TOKEN_ADJUST_PRIVILEGES)
    win32security.AdjustTokenPrivileges(th, 0, new_privs)


def low_priority(pid):
    #  PROCESS_SET_INFORMATION, PROCESS_ALL_ACCESS
    proc = win32api.OpenProcess(win32con.PROCESS_ALL_ACCESS, False, pid)
    win32process.SetPriorityClass(proc, win32con.IDLE_PRIORITY_CLASS)
