### ISSUE TITLE
Can't assign new file endings

### ISSUE THREAD

**Issue by BaldwinTechnology** [Microsoft/winfile#212]
This problem occurs in x64 as well as in x86 versions of winfile.

wfassoc.c L:2542

 `  dwError = RegSetValue(hk, pFileType->lpszBuf, REG_SZ,
      &pFileType->lpszBuf[pFileType->uDesc],
      lstrlen(&pFileType->lpszBuf[pFileType->uDesc]));
`
returns 5

A new window says: "Access denied."

hk is set to 0x80000000 in x86 and 0xffffffff80000000 in x64 version.

What am I doing wrong?

**Comment by malxau** [comment]
The short answer is that you're not running winfile as Administrator and it's trying to update system wide registry keys, which fails.

While looking into this though, I watched the ExtClean function do something really bad.  This code is assuming a file extension can only be 8 chars (which is not true), and ExtClean can prepend a period to the string.  To do this it allocates a 9 char string on its stack, but at the end of the function it copies the result back into the 8 char buffer in the parent frame, trashing the stack.  Hitting this requires a 7 char extension so the buffer becomes a period, 7 chars, and a NULL, needing 9 chars.

**Comment by BaldwinTechnology** [comment]
That did it.
