### ISSUE TITLE
Project files are wrong for 64-bit builds

### ISSUE THREAD

**Issue by DrPizza** [Microsoft/winfile#22]
I'd do a pull request but I don't have VS2015 installed here so I've been building with 2017 and 2017 toolchain and so things might break.

The release|x64 configuration has the wrong preprocessor defines (they're the 32-bit ones; debug|x64 has the correct 64-bit ones), and it's also missing the additional .lib inputs.

**Comment by craigwi** [comment]
Fixed this issue in commit eebca1e4c0b7f4804468c5ece2af3d358037d9ae.
