### ISSUE TITLE
Improve UTF-8 support by incorporating UTF-8 wrapper for Win32 ANSI applications

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [microsoft/winfile#222]
Here is the repository in question:
https://github.com/thpatch/win32_utf8

I will create an actual Pull Request for this later, as I am still working on creating a build. I have already forked the project for this reason (plus, I will be able to make any additional changes which I deem helpful).

**Comment by Amaroq-Clearwater** [comment]
I am running into some difficulties with developing my fork. The folder on my hard drive has become a mess of source files.

**Comment by craigwi** [comment]
Winfile is a Unicode app.  What benefit would be gained by this?
