### ISSUE TITLE
Use modularized windows.h replacement

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [microsoft/winfile#224]
There's an open-source replacement for the windows.h resource titled WindowsHModular, which makes it easier to exclude resources that are not needed for a given application and thereby cut-down on function bloat, while also potentially improving security and making code easier to manage.
- https://github.com/Leandros/WindowsHModular

However, implementing this may be a bit of a learning curve, and it may also conflict with implementing win32_utf8.h unless additional modifications are made.

**Comment by craigwi** [comment]
While interesting to see, I don't see the benefits for this project.
