### ISSUE TITLE
Enhancement: Alternate Data Stream and NTFS Link manipulation/browsing

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [microsoft/winfile#226]
Giving WinFile the ability to view, browse, manipulate and create Alternate Data Streams, Symbolic Links, Hard Links and Folder Junctions (all features of NTFS), and in a user-friendly manner, would greatly increase the versatility of the program... Not only as a file manager, but also as an administration tool, especially in the context of security Identifying if a otherwise benign file has a malicious executable or script hidden inside of it by means of ADS would be an invaluable asset in infosec fields).

**Comment by Amaroq-Clearwater** [comment]
A further extension to this, which I actually forgot in my initial comment, would be the ability to use Native API functions to scan for files which are not visible via WinAPI; the Native API uses a different form of text encoding, and thus is able to see files and folders with names which begin with a NULL character and would thus be invisible to normal WinAPI programs (as the NULL character is used to terminate strings in ANSI and UTF-8). This tactic is commonly used by malware authors to hide things from the operating system, such as malicious files and registry keys.

**Comment by 29039** [comment]
Just a heads up, that browsing files in 7-zip (I'm on version 19.00)  gives you an option for "Alternate streams" in the context menu of a file. Not sure if that it helpful to you or not.
