### ISSUE TITLE
Unable to dismount external drive / thumb drives due to file manager lock

### ISSUE THREAD

**Issue by ScottHollows** [microsoft/winfile#229]
ISSUE
Unable to dismount external drive / thumb drive due to File Manager has a lock on the drive after the drive is displayed in File Manager

STEPS TO REPRODUCE
1) Insert a thumb drive and wait a few moment so its gets mounted as a drive letter such as F:
2) start file manager
3) view the thumb drive in file manager
4) try to safely dismount the thumb using the standard process.
- click on the thumb drive icon in the task bar notificaiton area
- dismount the drive by selecting "eject <thumb drive name>"
- you will see an error message similar to this ...
Problem Ejecting USB Mass Storage Device
This device is currently in use. Close any programs or windows that might be using the device, and then try again.

This issue also occurs in other scenarios such as when you view the drive in file manager, then swap to viewing another drive which means the external drive is no longer appearing in a file manager window.

WORKAROUND
Exit file manager which will release the lock on the drive and then try to dismount the drive

REQUESTED CHANGED
This is not a big deal if the drive is currently visible in a file manager window, however if the drive is no longer visible in a window I think the locks should be released which would allow the drive to be ejected by the user

SCREEN SNAPSHOT
Screen snapshot show the error message when trying to dismount the drive after viewing the drive in File Manager

![image](https://user-images.githubusercontent.com/4010210/60764877-15b92480-a0c4-11e9-8bd6-2fee57cf9ef1.png)

**Comment by ScottHollows** [comment]
Screen snapshot show the error message when trying to dismount the drive after viewing the drive in File Manager

![image](https://user-images.githubusercontent.com/4010210/60764867-e9050d00-a0c3-11e9-9f0f-5c2a59a6dc7b.png)

**Comment by craigwi** [comment]
I have tried two things, one or both of which should work for you.  The one I just tried: using winfile, select a drive other than the thumb drive.  Then use Windows to eject the drive.  This worked for me.

If that doesn't work for some reason, then you can do the first part (switch to another drive) and then use the winfile Window.Refresh command.

**Comment by ScottHollows** [comment]
Im doing some cleanup on old issues that I logged

Craig provided a reasonable workaround.
I am closing this issue
