### ISSUE TITLE
File Manager does not see shared drives (Z:\) in VMWare Server

### ISSUE THREAD

**Issue by ScottHollows** [microsoft/winfile#231]
UPDATE - this issue is occuring in recent versions of File Manager available in this GitHub project as well as earlier versions of File Manager from Windows 2000

Issue
===========
When using a virtual machine within VMWare Server, you can share a folder (or drive) from the host so it will appear as a folder within Z: drive on the guest virtual machine

For example, you can setup C:\TEMP folder on the host so it appears as Z:\C_TEMP on the guest virtual machine.
The setup is done within the virtual maching settings in VMWare Server

The folder appears as Z:\C_TEMP in Windows Explorer - so that is good.
However, it does not appear in File Manager

Failed Workarounds
=============
I tried mapping a substitution drive to Z: drive but this did not work. 
The new Y: still did not appear in File Manager either
C:> SUBST Y: Z:\

Screenshots
=============
Setup in VMWare Server settings
![image](https://user-images.githubusercontent.com/4010210/61167417-5821ac00-a571-11e9-92c5-68df07c5a7a3.png)

The shared folders correctly appear with Z: drive in Windows Explorer on the guest VM
![image](https://user-images.githubusercontent.com/4010210/61167423-6a9be580-a571-11e9-91fe-49e002018974.png)

However, the Z: drive does not appear in File Manager
![image](https://user-images.githubusercontent.com/4010210/61167431-843d2d00-a571-11e9-837b-2aa221e61524.png)

**Comment by SamB** [comment]
Wouldn't, say, http://superuser.com be a better place to ask this question?

**Comment by ScottHollows** [comment]
CORRECTION - The issue is occuring with the latest version of File Manager 10.0

I tested using a Windows 10 virtual machine in VMWare Server

The shared folders appear in Windows Explorer under Z:\
but Z: drive does not appear in File Manager

Please fix this issue

Also, can someone else please verify this issue by reproduce this in VMWare Server

**Comment by ZanderBrown** [comment]
I imagine that people using VMWare Server on Windows 10 is a fair niche group so fairly unlikely to overlap with the 245 watchers, perhaps ask on a forum or similar to find others with the problem 

Do any other programs have this problem? Not impossible VMWare is doing something wrong

**Comment by Daniel15** [comment]
Try connect a network drive in File Manager itself (Disk &rarr; Connect Network Drive, select any drive letter, use `\\vmware-host\Shared Folders` as the path) and see if that works?

**Comment by ScottHollows** [comment]
Thanks Daniel.  That worked.

This issue can be closed as this is a reasonable workaround and it only affects a small number of users

In case anyone else experiences this issue, this is what I did ...

1) Create a file STARTUP.BAT with this content
subst K: "\\vmware-host\Shared Folders"

2) setup a task in Windows job scheduler to call my batch file.
The job is scheduled to run when the VM machine starts.
If it does not work, configure the job to have a delay of 5 - 10 seconds and try again
