### ISSUE TITLE
Start store app with "winfile" from command line

### ISSUE THREAD

**Issue by fubar-coder** [microsoft/winfile#235]
It would be nice if I could start the file manager from the command line using the `winfile` command.

**Comment by ScottHollows** [comment]
This already works.   Have you tested it ?

winfile.exe needs to be in the windows search path, although using the registry APPPATH might work

**Comment by fubar-coder** [comment]
I did the following:

* Install the file manager from the store
* Open the shell (either cmd.exe or PowerShell)
* Enter `winfile.exe`

Result:

Command not found

What I want:

The apps in the store are able to register some kind of "alias" to make it callable from the shell, which will automatically be available when the app gets installed.

What I do not want:

Find the cryptic path to the store app executable (`C:\Program Files\WindowsApps\Microsoft.WindowsFileManager_10.1.3.0_x64__8wekyb3d8bbwe\Winfile`) and add it to my path manually.

**Comment by ScottHollows** [comment]
got it.  so this is an enhancement request for the app store installer to add an registry to one of these paths, which will do the magic mentioned abnove

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\App Paths

Im not 100% sure on this, but I think the first one is for Windows 32, the other is for Windows 64

Doing this will also allow file manager to be started from other ways to launch the app, such as a desktop icon or Start >> Run menu

I support this enhancement request.  It sounds like a good idea to me.

**Comment by craigwi** [comment]
makes sense.

**Comment by sirredbeard** [comment]
Wouldn't this simply require the addition of an AppExecutionAlias in the Appx package manifest?

**Comment by craigwims** [comment]
This appears to be addressed by #259.

**Comment by wojtekpolska** [comment]
> This appears to be addressed by #259.

doesn't seem to work on my end

**Comment by malxau-msft** [comment]
@wojtekpolska When you say it doesn't work, note that it hasn't been merged; did you perform a private build with it?

Looking at the differences between #259 and https://github.com/microsoft/terminal/blob/a6a0e44088ab768325665308367ac016a2534891/src/cascadia/CascadiaPackage/Package.appxmanifest#L161C1-L165C26 , I don't think it should have the extra `Winfile\` but other than that it looks right.

**Comment by malxau-msft** [comment]
This should be working in the latest store release.  Please let me know if there are any further issues.
