### ISSUE TITLE
Feature Request - Shortcut key for Create New Folder - CTRL+SHIFT+N

### ISSUE THREAD

**Issue by richardboegli** [microsoft/winfile#238]
Shortcut key for Create New Folder - CTRL+SHIFT+N, like in Windows Explorer

**Comment by craigwi** [comment]
It already works that way.  This line in res.rc:

"N",        IDM_MAKEDIR,    VIRTKEY, SHIFT, CONTROL, NOINVERT

is just that: ctrl+shift+n means to create a new directory.
