### ISSUE TITLE
A couple of suggestions and a small nit to pick 

### ISSUE THREAD

**Issue by Al-Kalian** [Microsoft/winfile#24]
Your effort is to be praised, 

I've been using WinFile since it first came out, and still use it every day. Unfortunately it got broke in Vista and this guy figured out a fix for it: http://people.ee.ethz.ch/~davidsch/vistafm/

It was a bit fiddly to get it to work, but it did work under Vista, Win-7 and Win-10. But there were a couple of problems mainly dealing with permissions, and Winfile.ini not being saved every time. Specifically in the Windows32 directory, the ECT directory didn't show up in David's version. It shows up fine in yours. Another one was the WinEvt sub directory with the Event Logs. It didn't show up in Davids but shows up fine in yours. I'm sure there are others but it looks like your version solved all of the missing sub-directories.

The link given in the How to Geek article works: Visual C++ Redistributable for Visual Studio 2015 and you have the option of choosing a 32-Bit version or 64-Bit version. I chose the 64 bit version and got: **The program can’t start because MSVCP140.dll is missing from your computer**. 

But when I installed the 32-bit version, the error message went away and File Manager started right up. I'm running Win-7 and the error message might not appear if you are using Win-10. But it might be a good idea to let How to Geek know that they should mention to download the 32 bit version. 

Your version of File Manager worked flawlessly and as I used it, something was a bit different from the original version. I couldn't put my finger on it, and then I realized that it was how your version handled the display of the Directories and Sub-Directories. The original has a solid outline, and your version doesn't. It might have something to do with the newer libraries, dunno.

All in all, it's a welcome addition as far as I'm concerned.

Good job, well done.

![file-manager-hidden-files](https://user-images.githubusercontent.com/38224497/38514699-c2286242-3be6-11e8-8ab8-44dcc7cd03db.jpg)

![file-manager-folders](https://user-images.githubusercontent.com/38224497/38514777-f96f58a0-3be6-11e8-8aea-732bea2fa09f.jpg)

**Comment by Biswa96** [comment]
The dependency of VCRuntime DLL can be removed in the project file by changing the code generation as Multi threaded. See this: https://stackoverflow.com/questions/9052694/
