### ISSUE TITLE
Manifest file should include DPI Aware options

### ISSUE THREAD

**Issue by 07c0ff3a590b** [microsoft/winfile#240]
I've made this work using Resource Hacker so I can achieve clean DPI levels on Winfile

![image](https://user-images.githubusercontent.com/55628546/67442547-851a3c00-f601-11e9-87a3-dbfc0dd62f21.png)

Default DPI: 

![image](https://user-images.githubusercontent.com/55628546/67442554-9a8f6600-f601-11e9-81ca-1ce49325a594.png)

**Comment by craigwi** [comment]
What specifically do you think should be changed?

**Comment by nurky** [comment]
> What specifically do you think should be changed?

I have a huge monitor so I'm using DPI Scaling. I don't like going to Compatibility and setting the DPI levels myself, I think the application should default by itself.

What needs to be changed you ask? Inside the manifest file we should replace application tag with this:
```
<application xmlns="urn:schemas-microsoft-com:asm.v3">
  <windowsSettings  xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
    <ws2:dpiAwareness>PerMonitorV2</ws2:dpiAwareness>
  </windowsSettings>
</application>
```

This will enable the best DPI scaling Windows 10 has to offer.

**Comment by craigwi** [comment]
This appears to be the same basic issue as #19.  Can someone comment on whether the solution here will address the points made in issue #19?

**Comment by malxau-msft** [comment]
Closing this as a duplicate. We can continue the conversation about best next steps in #19 .
