### ISSUE TITLE
Please make a new stable release

### ISSUE THREAD

**Issue by Anixx** [microsoft/winfile#241]
The last one is two years old.

**Comment by craigwi** [comment]
The store version was released on 1/21/2019.  Which release are you referring to that is two years old?  And not stable?

**Comment by clzls** [comment]
@craigwi Maybe (s)he is thinking that [v10.0](https://github.com/microsoft/winfile/releases/tag/v10.0) is the latest "stable release"? :smile:

**Comment by Anixx** [comment]
I do not use the store.

**Comment by Anixx** [comment]
Wil there be any further non-store releases?

**Comment by craigwi** [comment]
Ahh.  Thanks for helping me understand.  I updated the README with all of the locations of the release.

**Comment by Anixx** [comment]
I cannot download the release from Azure

**Comment by craigwi** [comment]
There was a type in the x64 link.  That is fixed.
