### ISSUE TITLE
How to save current settings

### ISSUE THREAD

**Issue by keithg2005** [microsoft/winfile#245]
Not an issue, but an tip from an old user that I think needs to be documented. 

There is a setting to save current settings on exit, but if you setup the appearance the way you like it you have two options to have it open in the save way.

1) Set save settings on exit to yes, then save and reopen app and turn this setting off.
2) Hold down shift key and right double-click the upper left icon of the file image.  This will save the current settings to the default.

**Comment by craigwi** [comment]
Interesting; the following menu item and code already exist, just disabled:

#ifdef PROGMAN
#define IDM_SAVENOW         513
#endif

#ifdef PROGMAN
    MENUITEM    SEPARATOR
    MENUITEM    "Save Settings &Now",       IDM_SAVENOW
#endif

#ifdef PROGMAN
   case IDM_SAVENOW:

      SaveWindows(hwndFrame);
      break;
#endif

**Comment by malxau-msft** [comment]
I think this can be considered fixed by #423 .  Let me know if there are any further issues.
