### ISSUE TITLE
in BagOValues.h

### ISSUE THREAD

**Issue by nietoperz809** [microsoft/winfile#247]
#include <string>

... is missing. otherwise, the compiler doesn't find 'wstring'

**Comment by craigwi** [comment]
I don't understand.  What is include is missing where?  And what means are you using to compile?

There are no such issues using Visual Studio.

**Comment by nietoperz809** [comment]
I use VS community 2019
I must `#include <string>` at the top of this file, otherwise wstring is'n found.

**Comment by nietoperz809** [comment]
I use VS community 2019
I must `#include <string>` at the top of this file, otherwise wstring isn't found.

**Comment by craigwi** [comment]
Same here -- and I am not seeing the issue.  Perhaps I have certain VS feature packages installed that you don't...

**Comment by nietoperz809** [comment]
That can be the reason. I have kicked out much .NET stuff that I probably never will need.

After cloning the winfile from Github I double-clicked the sln-file to open the project. Then I had it to retarget it to 'v142' since I haven't vs 2017 build tools installed.

**Comment by craigwi** [comment]
So this could be an issues with the v2 2019 tools?  Seems like a simple fix in any case.

**Comment by nietoperz809** [comment]
It looks like the c++ header 'string' is already known by the compiler in your setup.
perhaps a compiler switch?

btw, some months ago I've built winfile from the leaked win2k sources, and progman too, that was much fun :)

**Comment by craigwi** [comment]
I doubt it is a compiler switch since that would be part of your build too.

I have VS 2017 installed too and Winfile rebuilds cleanly.

Thus it looks like an issue when re-targeting Winfile to 2019 tools.  Can others confirm?

**Comment by craigwi** [comment]
I talked to the C++ team yesterday that deals with this and they said there was probably a refactoring of the includes and it was reasonable to just add the #include as suggested.  Thanks @nietoperz809.
