### ISSUE TITLE
Can the old revisions be published as well?

### ISSUE THREAD

**Issue by flarn2006** [microsoft/winfile#253]
I noticed that if I set File Manager as the shell in Windows 3.1 (in SYSTEM.INI) it will actually give me the "This will end your Windows session" prompt when I exit, like it would in Program Manager. I got curious what exactly it checks to determine whether or not to display this message. I decided to look at the source code, remembering it had been published, and I found the message, but it's commented out and there's no code that references it. Does Microsoft still have the old revisions of the source code, and if so, could you post those as well for posterity?

(Fun fact: the non-Y2K-compliant version included with Windows 3.1 will display the 2-digit form of the year 2023 as "<3".)

**Comment by craigwi** [comment]
I never found the source code for versions of Winfile prior to the one I released.  Sorry.

**Comment by flarn2006** [comment]
Alright, no worries; just thought I'd ask. Thanks for releasing this one at least! And for responding to my comment :)
