### ISSUE TITLE
Publish Winfile to Winget

### ISSUE THREAD

**Issue by lorisobi** [microsoft/winfile#255]
I think the Windows File Manager should be also published to Windows Package Manager Community repo (https://github.com/microsoft/winget-pkgs) to keep the installation simple and intuitive.

**Comment by ZanderBrown** [comment]
> keep the installation simple and intuitive

Our installation is so simple and intuitive it doesn't exist, you just run the exe

**Comment by clzls** [comment]
> > keep the installation simple and intuitive
> 
> Our installation is so simple and intuitive it doesn't exist, you just run the exe

Before running you should download it from this repo or MS store:) Maybe what lorisobi think is to make the update process simpler; however WinFile may seldom need an update.^_^

**Comment by lorisobi** [comment]
i mean at the end winget is for users nothing else, than a command line app store. Winfile is published in the classic microsoft store so it could also be published in the package manager library

**Comment by ZanderBrown** [comment]
Sure, no harm in it

Point is it doesn't need simplifying

**Comment by lorisobi** [comment]
https://winstall.app/apps/Microsoft.winfile

Can be closed now - Winfile is now listed on winget

**Comment by clzls** [comment]
> https://winstall.app/apps/Microsoft.winfile
> 
> Can be closed now - Winfile is now listed on winget

You may close it yourself - or call @craigwi to help you:)
