### ISSUE TITLE
Links not showing properly

### ISSUE THREAD

**Issue by diegodcarg** [microsoft/winfile#264]
Directories Links (i.e. mklink /D) are showed in File Explorer as common directories and when right-clicked and asked for properties IN THE RIGHT PANEL an error is displayed: "windows can not find XXX"
Good work on the app! thx!

**Comment by craigwi** [comment]
There is something odd going on.  When I select the link in the right panel the first time, I get the error you mention.  If I double click the name in the right panel, I get a non-existent drive loaded with the driver letter the first letter of the link name (which in my test was 'link').  If I go back to the original drive and right click on the link in the right panel it works this time.  Hmm.

**Comment by schinagl** [comment]
I guess I solved this with #284

**Comment by craigwi** [comment]
@diegodcarg, if you concur, close this issue.

**Comment by schinagl** [comment]
@diegodcarg: Can we close this?
