### ISSUE TITLE
[Junction Points] Could they use a different icon to regular directories?

### ISSUE THREAD

**Issue by dftf-stu** [microsoft/winfile#269]
Could _Junction Points_ get a different icon in a future update please, as currently they just use the same yellow folder icons that regular directories use, so they look no-different.

Maybe just copy the directory icons, but change the yellow colour to grey?

Compare _Windows File Manager_ and _File Explorer_:
![Winfile_JunctionPointsLookLikeFolders](https://user-images.githubusercontent.com/83965343/120023935-5f77c480-bfe6-11eb-88d5-6ee672aa016b.png)

**Comment by malxau** [comment]
@craigwi Can this be closed now #304 is merged?
