### ISSUE TITLE
Copy/Edit Address

### ISSUE THREAD

**Issue by rothgecw** [microsoft/winfile#270]
This isn't so much an issue as an idea for consideration. I was looking for a good way to copy the path at the current directory, but the best I could come up with was to go to properties and copy from there. My simplest suggestion would be to offer an option to copy current path to clipboard. A more complex idea would be to offer an address bar at the top of the main/child window that can be copied or edited (effectively using the Goto Directory functionality).

Thanks so much for bringing Winfile back to life!

**Comment by SirToffski** [comment]
I've found a quick workaround: using <kbd>CTRL</kbd>+<kbd>F</kbd> and copying the path from there.

![image](https://user-images.githubusercontent.com/47118864/145810135-32e04325-9074-4e18-bfec-c5ca3528d86c.png)

**Comment by schinagl** [comment]
Or: Comes already from my spine
ALT + F R 
CTRL + C

**Comment by SirToffski** [comment]
> Or: Comes already from my spine ALT + F R CTRL + C

@schinagl  Neat! Though only a file name is copied with your method, not the path ;)

<kbd>ALT</kbd>+<kbd>F</kbd> <kbd>R</kbd> : file name is copied.

![image](https://user-images.githubusercontent.com/47118864/151176366-c48c8054-0997-4ed1-860e-7ea417e0a9a5.png)

<kbd>CTRL</kbd>+<kbd>F</kbd> : no file name, but the directory the file resides in

![image](https://user-images.githubusercontent.com/47118864/151176624-b0bb9336-1bc7-4089-b66c-069d9be9ab16.png)

Whilst both are useful, @rothgecw was specifically wondering about the path:

> I was looking for a good way to copy the path at the current directory

**Comment by rothgecw** [comment]
@schinagl, @SirToffski, thank you both! Either way seems equally viable, only that the `ALT`+`F` `R` requires the file's parent directory to be selected. I really appreciate both options. Cheers!

**Comment by schinagl** [comment]
I was inprecise... ( Since I really work with Winfile all day, the hotkeys are hardcoded to my brain already :-)

1) You want the full path and you are in the right pane:
ALT + F R
CTRL + C
CTRL + F
CTRL + V
Cursor up
CTRL + C

Full path and filename in copy buffer

This sounds long, but is typed in half a second if you did it a few times

2) You are in the left pane
ALT + F R
CTRL + C

You get the path in the copy buffer

Most times I use 1)

**Comment by schinagl** [comment]
Was this issue solved with #295?
Can we close it?

**Comment by rothgecw** [comment]
Yes, that looks like a very good solution. Thank you!

Any idea when a new build will be created?

**Comment by schinagl** [comment]
@craigwi is the boss here ;-) 
If you ask me, it would be nice to roll a release by mid year as soon as we have some more PRs in?
In the meantime you could grab a build from my branch (_hermann), which has the master and all of my PRs in from
https://schinagl.priv.at/nt/winfile/winfile.html
