### ISSUE TITLE
Incomplete directory listing in ExFAT file system

### ISSUE THREAD

**Issue by bthies-dev** [microsoft/winfile#274]
I am not sure if this is an issue of ExFAT and Winfile, or large drives in general and winfile. Will test with a 3TB drive later to see if I can reproduce it.
![winfile](https://user-images.githubusercontent.com/11824771/125363496-b2ab9980-e33e-11eb-8a38-5ba9a05799aa.PNG)

**Comment by craigwi** [comment]
any luck reproducing this?

**Comment by malxau** [comment]
Show hidden/system files appears to be disabled by default.  Are these folders marked with those attributes?  This can be toggled with View, By File Type.

It also looks like after changing this setting the right pane is refreshed but the left pane is not.

**Comment by craigwi** [comment]
The last point "It also looks like after changing this setting the right pane is refreshed but the left pane is not." is a bug I have seen before.

**Comment by schinagl** [comment]
@bthies-dev : Does #299 solve your problem? And thus your issue is solved and can be closed?

**Comment by malxau-msft** [comment]
I don't think there's anything actionable here.  Please reopen if there's a case of Winfile not being able to see files that explorer can see that we can investigate.
