### ISSUE TITLE
Windows 11 File Explorer does not show year 1601 or year 9999 in the column

### ISSUE THREAD

**Issue by gitbbkload** [microsoft/winfile#277]
[1601+9999.zip](https://github.com/microsoft/winfile/files/7155695/1601%2B9999.zip)

Good day,

I have found a problem in Windows 11 File Explorer, it does not show in the column (Date modified, Date created, Date accessed) the year 1601 or year 9999. Winfile has no problems.

![Screenshot 2021-09-14 004900](https://user-images.githubusercontent.com/90634153/133116687-57040283-d991-4926-bd10-beeeeb305f24.png)

Can one of you test if this is also the problem on your side? I use NTFS as file system.
The .zip file must be extracted with [7-Zip](https://7-zip.org/download.html) because Windows 11 File Explorer internal zip function cannot set the timestamps (year 1601 and year 9999) correctly.

7-Zip shows the year 1601 and year 9999 inside the .zip file.

![Screenshot 2021-09-14 005235](https://user-images.githubusercontent.com/90634153/133116940-b6ca3c47-aff1-4319-ab5e-816b1b9bf935.png)

**Comment by craigwi** [comment]
You should report the issue in a forum about Windows 11.

**Comment by gitbbkload** [comment]
> 
> 
> You should report the issue in a forum about Windows 11.

Which forum? Where can I find the Windows 11 File Explorer developers? Can you fix it for Windows 11 File Explorer?
