### ISSUE TITLE
TypeAhead is buggy in rare situations

### ISSUE THREAD

**Issue by schinagl** [microsoft/winfile#286]
Assume you have the following files in a directory

schin.jpg
sec1.bla
sec2.jpg
sh.jpg
sim.txt
ssh.ext

If you start typing in the right dir pane with 's' 's' 'h' the selection lands on sh.jpg. This means if the first two characters are the same, the second is swallowed, and it matches sh.jpg. This is a bit od, because if you rely on typing you end up on the wrong filename.

Explorer.exe behaves differently: ... it simply works :-)

Anyhow I already found the place where things go wrong in TypeAhead() in wfutil.c, but haven't found a proper solution, since this hydraulics is really tricky. Will investigate on

**Comment by craigwi** [comment]
TypeAheadString (which I added) makes a context-free decision about what to do with repeated characters.  Adding context, such as the list of files being checked, would require passing in the list (or the hwndLB), to do something smarter.  Unfortunately, the two places that would need to change store listbox data in different ways...
