### ISSUE TITLE
File Manager is listed in the HoloLens 2 a store, but app does not function on HoloLens 2

### ISSUE THREAD

**Issue by AMollis** [microsoft/winfile#292]
File Manager is listed in the HoloLens 2 app store, but app does not function on HoloLens 2.

1. Visit the Microsoft Store on HoloLens (which is ARM/ARM64 platform)
2. Search for and install Windows File Manager
3. Attempt to launch File Manager
4. File Manager fails to launch...

**Comment by craigwi** [comment]
Is there an emulator for the HoloLens or can someone run a debug build and/or help figure out what is wrong?  The ARM release of winfile was verified at one point on ARM.

**Comment by malxau** [comment]
As far as I know Hololens was only trying to support UWP, not Centennial/Win32.  See https://stackoverflow.com/questions/38943938/project-centennial-apps-in-hololens-emulator .

I don't know anything about how store apps work, but it seems odd to me that `Package.appxmanifest` includes a TargetDeviceFamily for `Windows.Universal`.  Shouldn't it only be `Windows.Desktop`?

If I'm reading [the docs](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-targetdevicefamily) correctly, the current package claims to be a Universal app, but imposes a minimum build of 14393 on Desktop (the section at the bottom.)  I think it wants to be Desktop only, with a minimum build of 14393.

**Comment by craigwi** [comment]
I can change the TargetDeviceFamily and/or just avoid targeting HoloLens next time I upload a store version.
