### ISSUE TITLE
Goto Cache Matching only full words

### ISSUE THREAD

**Issue by schinagl** [microsoft/winfile#296]
What is the intended behavior when it comes to matching strings in the Goto dialog:

Assume I have a directory 'c:\bla\ISSUE-123456 TC064\foo.txt'

When I type 'TC064' it matches. So far so good.
If I type '123456' it does not match, but it matches when I type 'ISSUE'. It also does not match when I type 'C064'

I would expect it also to match '123456', or 'C064'

So what should it be by design?

**Comment by craigwi** [comment]
I created this feature and I support improving it.  The data structure is a Trie which is setup to match on word prefixes where words are simply space separated substrings.  A simple change would be to increase the number of punctuation characters.

**Comment by clzls** [comment]
(Have seen it at the bottom of my inbox) The feature seems to work well when a language use spaces to separate words, but it's not the case of Chinese, Japanese or some other language (Vietnamese use spaces to separate syllables!). We do not use space to separate words. So when I try to search "智能"(Intelligence), I would expect "人工智能" (Artificial Intelligence) or "人工智能研究" (Artificial Intelligence Research) in my list.
