### ISSUE TITLE
can't open hidden/system/special folders?

### ISSUE THREAD

**Issue by scuq** [Microsoft/winfile#31]
maybe I'm missing something but I was not able to open or see for example my profile AppData, also Ctrl+G - C:\Users\myusername\AppData or Ctrl+G -> %AppData% isn't working, would be great if you could fix this. 
As I've read junctions should be shown as such, it would be great if redirected special folders like "Documents" or "Pictures" would be shown as redirected, respectively it would be desirable to follow them (as long as they are local) in an easy way, like clicking or ctrl/alt-clicking them.

**Comment by craigwi** [comment]
I am not having a problem with Goto "c:\users\craigwi\appdata".  %appdata% is not expanded at present.

Regarding the Documents and Pictures folders, they aren't redirected (at least not on my system).

If you look at "C:\Documents and Settings", you will see "C:\Users    <JUNCTION>" on the right.  Same for the other reparse points such as "C:\Users\All Users" (which is a SYMLINKD).

**Comment by T8z5h3** [comment]
the my pictures and my documents well folders are really shown as libraries witch is a new concept from vista or win 7. so they don't seem to act the same way as say %appdata%

**Comment by craigwi** [comment]
"c:\users\craigwi\My Documents" does show up as a JUNCTION point.  

At this point, I don't see anything to fix here.

**Comment by scuq** [comment]
![image](https://user-images.githubusercontent.com/10185017/38573857-95b376b8-3cf7-11e8-90ac-a674a56d22e5.png)

AppData folder isn't showing up, tested on 3 different windows 10 machines, 32 and 64bit build compiled with vs2017:

![image](https://user-images.githubusercontent.com/10185017/38573974-e5afec64-3cf7-11e8-890f-23b4b58f586c.png)

**Comment by scuq** [comment]
regarding the "My Documents", whether they are junctions or libraries or both, their location can be changed by right-clicking them in explorer, shows up like this:

![image](https://user-images.githubusercontent.com/10185017/38574494-37034128-3cf9-11e8-9ddd-de240165e37f.png)

I think their location/redirection is stored in

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders

since they are not junctions they appear empty if you change into the directory on the command line, but if you click them in explorer the redirection of the shell folder is transparent to the user, you just see the contents, regardless of the real folder location, it would be nice if this could be implemented in winfile.
