### ISSUE TITLE
Winfile is an explorer for busy systems

### ISSUE THREAD

**Issue by Fell** [microsoft/winfile#311]
I discovered this project a few days ago, and like many others I was delighted to to see the revival of winfile.

I just wanted to add my 2 cents, as I actually see a genuine use case for this little piece of software.

I personally use winfile as a high performance alternative to the Windows 10 Explorer. The Explorer can do a lot of cool things, but when the system is busy it can slow down significantly. Lots of plugins and thumbnail generators are nice, but sometimes are just slowing down the experience to a halt.

Winfile is much more lightweight, without compromising much functionality. I can still copy, move and delete as much as I want, even when 3 cloud sync applications are indexing changes in the background and hashing files.

So I just wanted to say: Please keep it as fast as it is, or even improve on it. I love it.

Feel free to close this issue after a while, it's just an opinion.

**Comment by craigwi** [comment]
The goal here is to stay pretty close to the original and that includes speed.  Thanks for your coment.
