### ISSUE TITLE
how to no open multiple istance of winfile?

### ISSUE THREAD

**Issue by marcorocco2102** [microsoft/winfile#314]
Hi,

if I clic on the winfile icon it open winfile, and if I click another on the icon it open 2 istance of winfile and each time another istance.
Is there a way to tell to windows or winfile that it have to open only one time and the same window of the program, not other istances? thanks

**Comment by malxau** [comment]
I think we'll need @craigwi's help to answer this.

The original WinFile had code for this, but it's commented out.  I don't see it commented out in the NT sources, this looks to be a change that happened as part of the original open source release, and I don't know why:

```
1326    //
1327    // Check to see if another copy of winfile is running.  If
1328    // so, either bring it to the foreground, or restore it to
1329    // a window (from an icon).
1330    //
1331    {
1332       HWND hwndPrev;
1333       HWND hwnd;
1334
1335       hwndPrev = NULL; // FindWindow (szFrameClass, NULL);
1336
1337       if (hwndPrev != NULL) {
1338          //  For Win32, this will accomplish almost the same effect as the
1339          //  above code does for Win 3.0/3.1   [stevecat]
1340
1341          hwnd = GetLastActivePopup(hwndPrev);
1342
1343          if (IsIconic(hwndPrev)) {
1344             ShowWindow (hwndPrev, SW_RESTORE);
1345             SetForegroundWindow (hwndPrev);
1346          } else {
1347             SetForegroundWindow (hwnd);
1348          }
1349
1350          return FALSE;
1351       }
1352
1353    }
```

**Comment by schinagl** [comment]
I remember this singleton behavior of the original Winfile, and was very pleased to see it is gone in this release.

**Comment by craigwi** [comment]
yes, I removed this early on.  I achieve what @marcorocco2102 desired by pinning to the task bar in position 2 and then using <windowskey>+2 to start or bring to the foreground a single instance.

**Comment by malxau** [comment]
I don't have an opinion on this either way, but just out of curiosity - since WinFile is an MDI application that allows multiple child windows, what's the scenario where it's desirable to have multiple parent windows/instances?

**Comment by schinagl** [comment]
When you work on different topics and want to group things: Each Winfile has 2 child windows open and you copy back and forth between the two child windows.
