### ISSUE TITLE
Permission icon on toolbar not working

### ISSUE THREAD

**Issue by schinagl** [microsoft/winfile#320]
Is the permissions icon on toolbar supposed to work?
![PermissonsIconGrayedOut](https://user-images.githubusercontent.com/7418603/166120167-06043ff3-c29e-4702-941b-aec306cf049e.png)
Internally it uses acledit.dll, which is still there and can be loaded in wfinfo.c:1772, but on the first call with FMEVENT_LOAD it fails.
This is why winfile unloads the .dll and the icon is grayed out further on

So there are few questions:
- Is acledit@FMExtensionProcW deprecated completley with W10/W11? Think so.
- On which plattforms does acledit@FMExtensionProcW work? WNT4/W2K/WXP/W7?
- On which plattforms shall this Winfile work? W7/W10? or below?
- If acledit@FMExtensionProcW is deprecated, is there a replacement for this call? I doubt because FMExtensionProcW is too specific

**Comment by malxau** [comment]
- Not just deprecated, it's fully gone - it does nothing except return zero.
- NT4/W2K/XP (32 bit only.)  It was never ported to 64 bit and was removed in Vista.
- I'm not actually sure...? I think Vista+?  My tree targets 2000+, which requires changes not in this one.
- I need to do more research here.  Like the other issue, one starting point would be to see what Explorer does, although it also might not be documented.  Obviously the raw functions to change file permissions are documented, so the part that's missing is the UI.  So one option would be to use explorer's UI; one would be to build new UI; one would be to take acledit from an old OS (that's a joke); another would be to try to release the source for the old acledit.  I'm really not sure how Craig was able to release winfile to begin with (I've never succeeded at releasing code) so don't know how feasible that last one is.

**Comment by schinagl** [comment]
This repository seems to support W7/W8/W10/W11, since it is bound to WINVER==0x0600

So we could remove the 'security' icon for this version.

**Comment by schinagl** [comment]
Fixed with #324
