### ISSUE TITLE
Drag in works; out not so much

### ISSUE THREAD

**Issue by tig** [Microsoft/winfile#36]
Hi Craig :-)

Dragging & dropping from the Win10 shell (or other apps) INTO WinFile works fine.

But I get the universal-no cursor when trying to D&D *from* WinFile elsewhere.

Copy/Paste works both ways. 

I couldn't find any drop-source code (e.g. no impl of IDropSource). So I'm guessing you didn't get to this side of the equation?

**Comment by craigwi** [comment]
Hey there  Charlie, nice to hear from you again.

And leave it to you to find the missing features in my OLE drag/drop implementation!  You are correct, the drag/drop support is limited right now.  Fire up VS and send me a PR!

**Comment by tig** [comment]
I've been itching for something to un-rustify my C/C++ skills. We shall see. Hugs.

**Comment by craigwi** [comment]
I look forward to your PR.

**Comment by vic-codes** [comment]
> I've been itching for something to un-rustify my C/C++ skills. We shall see. Hugs.

I realize this is a bit old now, but... any updates on this? 😃
