### ISSUE TITLE
Start command shell in Administrator mode (Ctrl Shift K) starts in wrong folder

### ISSUE THREAD

**Issue by ScottHollows** [microsoft/winfile#365]
**Issue)** If you press CTRL SHIFT K the command shell opens in Administrator mode with the current working directory being C:\Windows\system32

**Expected Behaviour** the current working directory should be the current directory in file manager

This issue only occurs when opening the shell in Administrator mode (CTRL SHIFT K).
It does not occur when opening the shell in normal mode (CTRL K)

When fixing the issue, please test for the current drive being C: and also test another drive as well as C: is the default

**Occurs in;**
- File Manager 10.1.4.0
- File Manager 10.1.4.49
- File Manager 10.2.0.0 - latest release
- 
![image](https://user-images.githubusercontent.com/4010210/206850044-debdb585-99fb-4d21-b04d-eb302364c166.png)

**Comment by schinagl** [comment]
I came around this too, but I doubt this is a bug but more a feature: 

The 'Start in' is explicitly ignored when elevation is performed so that malicious binaries can do less harm. 

We could overcome this by appending /k cd /d <path> when issuing cmd.exe

**Comment by craigwims** [comment]
Well, it is not by design, just a bug I never got around to fixing.

**Comment by schinagl** [comment]
Then lets change it: #367

**Comment by schinagl** [comment]
#367 has been merged. Can we close this now?

**Comment by ScottHollows** [comment]
I logged the bug.

I am closing it now as resolved

Thank you to everyone who helped with this
