### ISSUE TITLE
WinFile Portable released by PortableApps.com

### ISSUE THREAD

**Issue by JohnTHaller** [microsoft/winfile#368]
Greetings all. Thought you'd be interested to know that [WinFile Portable has been released by PortableApps.com](https://portableapps.com/apps/utilities/winfile-portable). It's a portable package in our open/open source packaging format. It includes a launcher that handles selecting 32-bit or 64-bit and adjusting paths as the user moves between machine either by moving an external drive around or syncing via OneDrive/Google Drive/etc. It also adjusts fonts to match the host OS as it moves. Here's a look at it running via our portable platform manager on Pop_OS!

![WinFileOnPopOS](https://user-images.githubusercontent.com/8020860/212159619-e326fb95-6c8a-4c21-9daf-27eabe570f4f.png)

**Comment by malxau-msft** [comment]
Thanks for the contribution, and for letting us know!
