### ISSUE TITLE
software and add-ons to edit and compile File Manager

### ISSUE THREAD

**Issue by ScottHollows** [microsoft/winfile#382]
What software and add-ons do I need to edit and compile FIle Manager from this Github repository ?

Are there any specific versions that I have to use or is the latest version ok ?

**Comment by malxau** [comment]
The "official" toolchain is Visual Studio 2019, with Windows SDK 10.0.18362.0 (19H1.)  Community edition is fine.

It does work on newer versions, but msbuild files tightly specify the compiler and SDK version, so these would need to be changed to suit your environment.

Alternatively, there's also a GNUmakefile for using gcc/clang.  I haven't used this and don't know exactly what would be needed; mingw + msys should work, as should llvm + msys, but I haven't verified this.  If you do and hit issues, please let us know or file a pull request.

**Comment by ScottHollows** [comment]
thank you Malxau
