### ISSUE TITLE
Create WinFile specific About box

### ISSUE THREAD

**Issue by random-ideas** [Microsoft/winfile#40]
Perhaps I'm off the mark on the intent, but the Help > About box shows winver but without user or org information (left in this). Super cool otherwise though!
![image](https://user-images.githubusercontent.com/37677613/38530126-2e9febfa-3cac-11e8-88f4-e93f6ebe0352.png)

**Comment by craigwi** [comment]
Read the source; wfcommand.c line 2083 is unchanged from the past and calls -- wait for it -- ShellAbout().

I do agree, however, that WinFile should have a proper about box.  Any takers?

**Comment by ZanderBrown** [comment]
To be in keeping with the original it would be great if someone could recreate the Win3X era ShellAbout
![screenshot from 2018-04-10 12-04-39](https://user-images.githubusercontent.com/17074021/38551695-c599e7c2-3cb1-11e8-9148-77089177226b.png)

**Comment by daniel-white** [comment]
I noticed they were different. Perhaps it has something to do with a manifest.

**Comment by Anixx** [comment]
On Win 8.1 it reports incorrect Windows version (6.2 instead of 6.3) and wrong build number.

**Comment by ZanderBrown** [comment]
@random-ideas @daniel-white @Anixx are you running in compatibility mode?

That would explain wrong build ext

**Comment by Anixx** [comment]
No. No compatibility mode. In Win8.1 the APIS had changed, all old progs show windows version as 6.2 build 9200 while newer programs show 6.3 build 9600

**Comment by craigwi** [comment]
I renamed the issue.  Feel free to submit a PR.

**Comment by matthewjustice** [comment]
I have a change almost ready for a simple about box, but I'm not sure what text to include. Below is a screenshot of what I have now. Suggestions before I submit a PR? Or I could just submit as-is and let others update the text as needed.

<img width="283" alt="winfile-about" src="https://user-images.githubusercontent.com/18629374/38585105-a6d4106c-3ce6-11e8-846d-dfc980544aea.png">

**Comment by ZanderBrown** [comment]
It's a good starting point

**Comment by matthewjustice** [comment]
@ZanderBrown - Thanks. PR #76 submitted.

**Comment by craigwi** [comment]
@matthewjustice's PR addresses this for now.
