### ISSUE TITLE
Support sparse files?

### ISSUE THREAD

**Issue by SCasarella** [microsoft/winfile#407]
Does the current version support sparse files? (It does not seem to as far as I can tell.) Any plans/solution?

**Comment by schinagl** [comment]
Not explicitly. 

It does not mark them as it does for compressed or encrypted files. 

Furthermore it 'flattens out' during copying files, because as far as I know CopyFileEx() does not support creation of sparse files. 

But moving/renaming/symlinking/... should work.

**Comment by malxau-msft** [comment]
I don't think there's anything actionable here.  Please reopen if there's a specific piece of sparse support that's being requested.
