### ISSUE TITLE
How to specify the destination

### ISSUE THREAD

**Issue by uhuntu** [microsoft/winfile#408]
Hi there,

I have a question, how to specify the destination like Move/Copy/Rename etc. dialog ?

For example like below, I would like to copy some file to another directory, but the "To" edit box are always empty to let me in.

![image](https://github.com/microsoft/winfile/assets/4939569/06ebe3ed-e29c-427e-b07c-248f509cd408)

I think it is hard to use right ? I do some research like #270 they said some hot keys to copy address (?)

Please let me know if I missed anything, I am new in winfile and I would write an addon for it.

--
hUNt0

**Comment by schinagl** [comment]
Type/copy the path to the destination into the to: field.
