### ISSUE TITLE
I am off

### ISSUE THREAD

**Issue by schinagl** [microsoft/winfile#411]
Thanks guys for beeing part of that Winfile community for a long time. We fixed many issues and brought stability to Winfile.
I am leaving and continuing the Winfile development for my needs on my local branch and will not contribute to the main winfile repo anymore.

I have abandoned all my open PRs, so you don't have to mess with them anymore

To be honest I am not amused how things are going
* Small PRs end in disucssions over and over like right now #409, which was the last ditch now to leave. 
* It takes me more time to defend PRs than doing them. Sorry I don't have the time.
* I don't expect the big UNC PR to ever go through. It is open since ~16 month and more or less ignored.

Feel free to check out my fork
   https://github.com/schinagl/winfile
which contains UNC support, and a few little other things which I find useful during the daily work

It also contains a [Decmber 2023 cumulative Release](https://github.com/schinagl/winfile/releases/tag/v10.2.1.0)

Hermann

**Comment by malxau-msft** [comment]
Thank you for the contributions you've made to Winfile over the years, I've particularly appreciated the fast responses to issues that users report which have helped to guide them in the right direction.
