### ISSUE TITLE
Update Winfile on Chocolatey

### ISSUE THREAD

**Issue by craigwi** [microsoft/winfile#426]
Hi @malxau, I got an email from an admin at Chocolatey about whether Winfile on Chocolatey is still maintained: https://community.chocolatey.org/packages/winfile/10.2.0.0.

You were added as a maintainer there, but some approval step still needs to be done.  Is that on your end or on Chocolatey?

**Comment by malxau** [comment]
Hi Craig, good to hear from you.  You were right – although I couldn’t see any UI indicating maintainership of Winfile, there was an email from a year ago with a link I needed to click, which took care of it.  I’ll let Paul know that no further action is needed.

**Comment by craigwi** [comment]
Yep, all set.  Keep up the great work on WinFile!
