### ISSUE TITLE
uwp version?

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/winfile#5]
with broadfileaccess now available on uwp platform of windows 10 can we have a FileManager version on uwp as well?

**Comment by Biswa96** [comment]
Why UWP? Feel the retro smell of this program and enjoy the "old" win32 experience.

**Comment by craigwi** [comment]
It is not a goal of this project to support anything besides a native (x86 / x64) desktop app.

**Comment by Scherlac** [comment]
There is so many fork out there! Did someone started working to port it on UWP? Maybe on Blazor :) ?

**Comment by craigwi** [comment]
The "official" UWP release is nearly ready.  See #85.
