### ISSUE TITLE
In executable properties the product name is "Win7 DDK driver"

### ISSUE THREAD

**Issue by Anixx** [Microsoft/winfile#53]
In executable properties the product name is "Windows (R) Win7 DDK driver"

**Comment by NazmusLabs** [comment]
Wow, interesting...I wonder what the device driver kit for Windows 7 have to do with Winfile...

**Comment by ZanderBrown** [comment]
Probably just copy pasted the manifest

**Comment by matthewjustice** [comment]
This should be fixed now in master with PR #89

**Comment by genghaibo** [comment]
8  src/Winfile.vcxproj
 @@ -109,7 +109,7 @@
        <AdditionalIncludeDirectories>.;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      </ResourceCompile>
      <Link>
 -      <AdditionalDependencies>ole32.lib;shell32.lib;shlwapi.lib;comctl32.lib;%(AdditionalDependencies)</AdditionalDependencies>
 +      <AdditionalDependencies>ole32.lib;shell32.lib;shlwapi.lib;comctl32.lib;mincore.lib;%(AdditionalDependencies)</AdditionalDependencies>
        <AdditionalLibraryDirectories>
        </AdditionalLibraryDirectories>
        <GenerateDebugInformation>true</GenerateDebugInformation>
 @@ -134,7 +134,7 @@
        <AdditionalIncludeDirectories>.;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      </ResourceCompile>
      <Link>
 -      <AdditionalDependencies>ole32.lib;shell32.lib;shlwapi.lib;comctl32.lib;%(AdditionalDependencies)</AdditionalDependencies>
 +      <AdditionalDependencies>ole32.lib;shell32.lib;shlwapi.lib;comctl32.lib;mincore.lib;%(AdditionalDependencies)</AdditionalDependencies>
        <AdditionalLibraryDirectories>
        </AdditionalLibraryDirectories>
        <GenerateDebugInformation>true</GenerateDebugInformation>
 @@ -167,7 +167,7 @@
        <AdditionalIncludeDirectories>.;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      </ResourceCompile>
      <Link>
 -      <AdditionalDependencies>ole32.lib;shell32.lib;shlwapi.lib;comctl32.lib;%(AdditionalDependencies)</AdditionalDependencies>
 +      <AdditionalDependencies>ole32.lib;shell32.lib;shlwapi.lib;comctl32.lib;mincore.lib;%(AdditionalDependencies)</AdditionalDependencies>
        <GenerateDebugInformation>true</GenerateDebugInformation>
        <SubSystem>Windows</SubSystem>
        <TargetMachine>MachineX64</TargetMachine>
 @@ -192,7 +192,7 @@
        <AdditionalIncludeDirectories>.;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      </ResourceCompile>
      <Link>
 -      <AdditionalDependencies>ole32.lib;shell32.lib;shlwapi.lib;comctl32.lib;%(AdditionalDependencies)</AdditionalDependencies>
 +      <AdditionalDependencies>ole32.lib;shell32.lib;shlwapi.lib;comctl32.lib;mincore.lib;%(AdditionalDependencies)</AdditionalDependencies>
        <GenerateDebugInformation>true</GenerateDebugInformation>
        <SubSystem>Windows</SubSystem>
        <OptimizeReferences>true</OptimizeReferences>

**Comment by matthewjustice** [comment]
@genghaibo your comment seems to reference the change made in PR #89 to add mincore.lib. Did you have a concern?
