### ISSUE TITLE
The color of the folder edge and tree is grey instead of black

### ISSUE THREAD

**Issue by Anixx** [Microsoft/winfile#54]
The color of the folder edge, "+" signs and the tree branches is grey instead of black
![clipboard_20180410](https://user-images.githubusercontent.com/1271736/38554208-30cfa23a-3cb1-11e8-98b6-98aefdf5d01b.png)

Original:
http://storage4.static.itmages.ru/i/17/0919/h_1505825396_3777912_92ff09bce8.png

**Comment by ttsirkia** [comment]
https://github.com/Microsoft/winfile/blob/master/src/wbbitmap.bmp vs. https://github.com/Microsoft/winfile/blob/master/src/bitmap.bmp

**Comment by Anixx** [comment]
So, what should I do to make them black?

**Comment by Anixx** [comment]
@NazmusLabs It is even running under the same OS (Win 8.1)

**Comment by ttsirkia** [comment]
The original branch contais the black version of the images:
https://raw.githubusercontent.com/Microsoft/winfile/original_plus/src/wbbitmap.bmp

**Comment by craigwi** [comment]
this was changed sometime ago (i.e., "before my time").  When I looked at the two bitmap files (wbbitmap.bmp and bitmap.bmp) it appears that the differences are non-trivial.  If someone wants to propose a specific change to revert to the older look, go for it!

**Comment by Anixx** [comment]
I am not sure this should be changed if we are still waiting for someone to fix it.

**Comment by NazmusLabs** [comment]
@Anixx yes, I was actually planning to test out the older bitmap to see how it looks. But trying to figure out the High DPI solutions took my focus off of this. But, now that you reminded me of this, I guess I'll take a shot at doing this now, Insh'Allah, and report back the results, if the application compiles. :)

**Comment by ttsirkia** [comment]
The fix is trivial as the original_plus branch contains the original bitmap with black icons.

**Comment by Anixx** [comment]
Or, alternatively change the color in the new one (I don't think changing one fixed color should be difficult).

**Comment by NazmusLabs** [comment]
@ttsirkia ouch! does it?? Well I should have thought about this before, given that I spent about an hour updating the image pixel by pixel to create a new, sharp, and more pleasing looking version. I'll need to see how my hand made version compares with the one in the Original_plus. I ensured that no existing details while decided to take some creative approach to add some additional details I felt would look better than how it originally looked (judging by the first picture you posted earlier).

Anyway, I've updated the image and successfully compiled the application with the new bitmap. Here's the before and after. The results speak for themselves.

Before: gray file icon outlines:
![winfile before with gray file outline](https://user-images.githubusercontent.com/5572377/39092276-54c105d2-45d8-11e8-9b60-d7767ada8ed2.png)

After: sharp dark file icon outlines:
![winfile after with sharp dark file outline](https://user-images.githubusercontent.com/5572377/39092270-457e1c7c-45d8-11e8-9310-806c376fba34.png)

And now, I will have to go back and take a look at the original bitmap that is supposedly still in the original_plus release. :)

**Comment by ttsirkia** [comment]
Wrote this already five days ago :)

**Comment by NazmusLabs** [comment]
@ttsirkia haha oopse. You are right! Well, in that case, I'll put the original bitmap as well as my version side by side to see how mine differs from the original. And it'll also allow you to see if I have accidently damaged an icons and also see the intentional changes I made, which, in my opinion, makes the folders look better than they do in the original.

Original bitmap found in Original_Plus:

<img width="120" alt="wbbitmap dib" src="https://user-images.githubusercontent.com/5572377/39092329-9362deb8-45d9-11e8-9a75-0111c1b15dff.png">

My update of the bitmap used in the latest master branch commit:

<img width="120" alt="wbbitmap" src="https://user-images.githubusercontent.com/5572377/39092340-c90f6914-45d9-11e8-913f-54cd84678e6b.png">
