### ISSUE TITLE
issues i see

### ISSUE THREAD

**Issue by T8z5h3** [Microsoft/winfile#58]
hi,
here is the list of bugs i see from windows 7 pro 64 bit:
-menu items share a directory is dimmed when file is selected
-menu item view or set permissions is dimmed when file is selected 

-under file  drop down the compress... and uncompress seem to work but not in a way expected (i expected it to be compress to zip)

-under drop down Disk item,format disk is dimmed ( well folder labeled C:\ is selected (behavor unexpected but i guess this was used with floppy disks not hard drives) 
--under drop down Disk item Share as and stop sharing is dimmed (unexpected, but i guess this is a deprecated pre windows smb sharing option) 

overall a good prodect

**Comment by craigwi** [comment]
Thanks @T8z5h3 for your thoughts.  Compress == file system compression, not zip.  The disk format question is discussed in issue #62.  The rest behave as expected for the code base.  Please suggest any additional issues you see.
