### ISSUE TITLE
Unable to view hidden or system files/folders

### ISSUE THREAD

**Issue by corbob** [Microsoft/winfile#71]
I am not seeing any option to turn this feature on. Windows Explorer is showing hidden files and folders.

**Comment by scuq** [comment]
missed the option too, in the meantime I've found it, maybe https://github.com/Microsoft/winfile/issues/31 helps

**Comment by corbob** [comment]
This is true. This seems to solve it for me. That'll teach me for not looking at closed issues when I open a new one.
