### ISSUE TITLE
Show files/folders with the Encrypted attribute in green

### ISSUE THREAD

**Issue by FairPlay137** [Microsoft/winfile#74]
In Explorer, files and folders with the Encrypted attribute show up as green, as long as you have the "Show encrypted or compressed NTFS files in color" folder view option checked. No such behavior exists here currently, since Windows NT 4.0 was from before NTFS 3.0 (Windows 2000). It'd be nice to see this functionality here. Below are two screenshots showing the folder coloring in Explorer, then in Winfile.
![windows explorer behavior](https://user-images.githubusercontent.com/10647627/38583570-48c0feea-3cc8-11e8-8140-1210c9eb8251.PNG)
![winfile behavior](https://user-images.githubusercontent.com/10647627/38583571-48d56c36-3cc8-11e8-8a30-585abd1a811e.PNG)

**Comment by Loridawn99** [comment]
> ****


>

**Comment by Loridawn99** [comment]
- [ ] 

- [](url)

**Comment by ZanderBrown** [comment]
@Loridawn99 your comments don't seem to be coming through

**Comment by craigwi** [comment]
Fixed in PR #133.
