### ISSUE TITLE
Linux port with wine

### ISSUE THREAD

**Issue by BlauerHunger** [Microsoft/winfile#75]
Please provide a make target for building this natively for Linux (e.g. Ubuntu 18.04 LTS or Debian 9 "Stretch") using Wine.

**Comment by BlauerHunger** [comment]
But afaik it's only for mingw on Windows, I'm looking for some way to easily build it using clang or gcc natively on linux to build this against wine as a native linux application

**Comment by ZanderBrown** [comment]
you'll need the mingw build chain and modify the Makefile a bit

`i686-w64-mingw32` doesn't seem to work because 64bit support is still WIP but the 32bit equivalent should be doable

**Comment by Artoria2e5** [comment]
It can be fun to make a half-native Linux build with winelib after gcc gets sorted out too!

**Comment by mcilloni** [comment]
It builds fine on Linux using MINGW + Clang (clang -target x86_64-w64-mingw32) with just a few tweaks to the Makefile. I guess it should work ok with GCC too.

**Comment by Artoria2e5** [comment]
@dulaman Cygwin & MinGW's winuser.h seems to have that type, while wine's doesn't. The definition found in Cygwin/MinGW is:
```C
typedef struct tagDROPSTRUCT {
	HWND hwndSource;
	HWND hwndSink;
	DWORD wFmt;
	DWORD dwData;
	POINT ptDrop;
	DWORD dwControlData;
} DROPSTRUCT,*PDROPSTRUCT,*LPDROPSTRUCT;
```

Maybe paste it in somewhere?

(P.S. run make with `make -k` so it will keep going through all the files and hit as many errors as it can.)

**Comment by ZanderBrown** [comment]
Pasting that into `winfile.h` after the last `#include` leaves us with `unknown type name ‘FM_EXT_PROC’`

**Comment by Artoria2e5** [comment]
Please just do a big `make -k` then. We should just find out all the missing things in winelib and fix them in one pass.

**Comment by ZanderBrown** [comment]
Okay so swapping `#include <wfext.h>` for `#include "wfext.h"` helps, it seems winelib's wfext.h is missing some definitions there as well but WinFile provides it's own

**Comment by austin987** [comment]
For those interested in building with winemaker, I sent the first header fix, reported at:
https://bugs.winehq.org/show_bug.cgi?id=45026

here:
https://source.winehq.org/patches/data/145052

I plan to submit more fixes as my free time permits in the next few weeks. Please subscribe me to any new bugs filed that are Wine related.

**Comment by BlauerHunger** [comment]
I just built the current wine-staging from its git and then tried building WinFile using `winemaker` and then `make`. That's my [https://pastebin.com/VTFbsrTh](`make -k`output).

**Comment by Artoria2e5** [comment]
@BlauerHunger There seems to a bunch of problems associated with `TCHAR` and `LPTSTR` being narrow (8-bit) instead of wide (16-bit). Maybe throw a `-DUNICODE` in for `CFLAGS` to make them wide?

**Comment by craigwi** [comment]
Which PR are we talking about?  Do we need this issue open still?

**Comment by ZanderBrown** [comment]
@craigwi I would say this is worth being open but the various issues we are discussing are wine's fault not winfile

**Comment by craigwi** [comment]
Agreed: definitely open to supporting tweaks to master the facilitate other versions, but I don't see any changes to make for wine at this point.
