### ISSUE TITLE
Resize tiled windows when Winfile window is resized

### ISSUE THREAD

**Issue by Anixx** [Microsoft/winfile#78]
It would be great if the MDI childs tiled like panels etc would automatically resize to fit the whole parent window when Winfile window is resized. Maybe implemented as an option.

**Comment by ZanderBrown** [comment]
That would be cool but incredibly complex

**Comment by Anixx** [comment]
@ZanderBrown just send the tile command each time after resize, maximize, restore.

**Comment by ZanderBrown** [comment]
But then tile has essentially become a toggle

**Comment by Anixx** [comment]
Possibly, adding a tile toggle would be a good solution.

**Comment by craigwi** [comment]
Sounds like Windows 1.0!  This idea, while interesting, is at odds with the way MDI child windows work.
