### ISSUE TITLE
In the confirmation options dialog, the group frame is overlapped by text label

### ISSUE THREAD

**Issue by Anixx** [Microsoft/winfile#83]
![clipboard_20180411](https://user-images.githubusercontent.com/1271736/38637761-a5a913d8-3dbb-11e8-835a-f9d191b7714a.png)

The bottom edge of the "Confirm On" group frame is barely visible because it is by 1 pixel overlapped by the check box label "Modifying System, Hidden, Read Only files".

**Comment by peterooch** [comment]
[winfile.dlg line 635](https://github.com/Microsoft/winfile/blob/master/src/winfile.dlg#L635)
`-CONTROL "Confirm On", IDD_TEXT, "button", BS_GROUPBOX | WS_TABSTOP | WS_CHILD, 5, 3, 158, 85`
`+CONTROL "Confirm On", IDD_TEXT, "button", BS_GROUPBOX | WS_TABSTOP | WS_CHILD, 5, 3, 158, 86`
![fix_conf](https://user-images.githubusercontent.com/3612577/38901732-0c886f24-42a6-11e8-99a7-b3d31efd79fe.PNG)
To add this change to my pending pull request (#101) or somebody else is willing?

**Comment by craigwi** [comment]
Resolved in PR #116.
