### ISSUE TITLE
Suggest to avoid confuse Filename on Unicode normalization (NFD/NFC)

### ISSUE THREAD

**Issue by okdk** [Microsoft/winfile#86]
I'm Japanese User.

In Japanese , "Hiragana" and "Katakana" include unicode's  Combining Character Sequence.
「 ﾞ (Dakuten: u3099 )」「 ﾟ (Han Dakuten: u309A )」
Ordinary, Windows Filename Use NFD.  (example:「パピプペポ」=\u30D1\u30D4\u30D7\u30DA\u30DD)
But MacOSX Use NFC. (exaple:「パピプペポ」= \u30CF\u309A\u30D2\u309A\u30D5\u309A\u30D8\u309A\u30DB\u309A )

Windows Explorer and Winfile 10.0 binary confuse Filename NFD and NFC.
I suggest to  Winfile add "Separating Combining Character Option".

Windows Explorer:
![send1](https://user-images.githubusercontent.com/4371451/38665467-fc2505da-3e2b-11e8-931f-61efd1fd1447.png)
Winfile v10.0:
![send2](https://user-images.githubusercontent.com/4371451/38665470-fc7ac6aa-3e2b-11e8-85a3-27014a1315a2.png)
I suggestion:
![send3](https://user-images.githubusercontent.com/4371451/38667248-72752838-3e30-11e8-8516-f312bf72b701.png)

Cause:
On MacOSX ,copying file to windows fileshare folder, auto convert filename "NFC to NFD".
But Some MacOSX software (example: Adobe InDesign CC) pass through  that's convert.

Unicode Normalization:
https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization

Dakuten:
http://glyphwiki.org/wiki/u3099

HanDakuten
http://glyphwiki.org/wiki/u309a

Dencode (NFC/NFD converter):
https://dencode.com/ja/string/unicode-normalization

**Comment by craigwi** [comment]
Hi @okdk, can you describe what WinFile would do differently?  I can't tell from your description above.

**Comment by mattn** [comment]
> Windows Filename Use NFD.
> MacOSX Use NFC

Really!? AFAIK, Windows use NFC, and Mac use NFD.

@craigwi Windows use NFC. So if we draw as NFD in Windows controls, we must use owner-draw.
