### ISSUE TITLE
Scrambled layout (in Release) / Exception (in Debug) when loading an extension

### ISSUE THREAD

**Issue by BaldwinTechnology** [Microsoft/winfile#87]
Hi,

I found a bug.
If you run the new winfile (with an extension loaded) the layout gets weird in release mode.
In debug mode it gets me an exception.

I have to add the line
`extButton.iString = "";`

The extension I am loading is WinFileN.dll
[http://www.hardcopy.de/sw4you.com/winfilee.php](http://www.hardcopy.de/sw4you.com/winfilee.php)

in tbar.c

line 1304 ff:
`     extButton.fsStyle   = (BYTE)lpButton->fsStyle;`
`      extButton.idCommand = lpButton->idCommand + extensions[iExt].Delta;`
`      extButton.fsState   = TBSTATE_ENABLED;`
`	  extButton.iString = "";`
`//	  extButton.dwData = 0; <- not necessary`

`      SendMessage(hwndExtensions, TB_INSERTBUTTON, (WORD)-1,
         (LPARAM)(LPTBBUTTON)&extButton);
`

PS:
Can't append an image (Something went really wrong, and we can't process that file. Try again)
It's an png that shows the result.

**Comment by BaldwinTechnology** [comment]
Hi craigwi,

here you have an example. It shows what I mean. I hope this is usefull.

http://www.filedropper.com/winfile-addon
(Can't upload anything over this gitbug message box)

**Comment by BaldwinTechnology** [comment]
Nice, I tried now with Vivaldi.
But Firefox doesn't work. (Maybe some script blocking issues. But github is whitelisted.)

[WinFile-AddOn.zip](https://github.com/Microsoft/winfile/files/1906635/WinFile-AddOn.zip)

**Comment by ZanderBrown** [comment]
Odd, works for me

**Comment by BaldwinTechnology** [comment]
![weirdlayout](https://user-images.githubusercontent.com/38319355/38728504-5d72077c-3f10-11e8-9915-e7583ed368ec.png)

Not for me.
The last button is the test addon.

**Comment by ZanderBrown** [comment]
(sorry i was meaning file upload, haven't tested the addon yet)

**Comment by craigwi** [comment]
@BaldwinTechnology, I checked in a change that appears to address the major problem.  Can you verify?

**Comment by BaldwinTechnology** [comment]
@craigwi All is fine. Thanks.
