### ISSUE TITLE
Suggest to setup in visual studio 2017

### ISSUE THREAD

**Issue by Htut** [Microsoft/winfile#96]
I am new to C++ and VS2017. I used Visual Studio 2017 community. When I build, I got error message as "Err TRK0005	Failed to locate: "CL.exe". The system cannot find the file specified." I found my CL.EXE file at unneath of folders "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin".

**Comment by craigwi** [comment]
Have you followed the instruction in the video https://www.youtube.com/watch?v=yQtWwEir2Ow? 

If so, what were the issues?

**Comment by Htut** [comment]
Hi, It work for me and fine now. I post issue "CL.EXE" not found error  and fine now after "Retarget Solution" at solution and 32-bits fine like you. Thanks you and amazing old Windows 3.0 (Last 30 years application still work on my screen. The feature I like most is working multiple windows side by side.) Great Job!.
